import { Flag } from '@keira/shared/constants';

export const ITEM_FLAGS_EXTRA: Flag[] = [
  { bit: 0, name: 'FACTION_HORDE - Horde only' },
  { bit: 1, name: 'FACTION_ALLIANCE - Alliance only' },
  { bit: 2, name: 'DONT_IGNORE_BUY_PRICE - When item uses ExtendedCost in npc_vendor, gold is also required' },
  { bit: 3, name: 'CLASSIFY_AS_CASTER' },
  { bit: 4, name: 'CLASSIFY_AS_PHYSICAL' },
  { bit: 5, name: 'EVERYONE_CAN_ROLL_NEED - Anyone can roll need' },
  { bit: 6, name: 'NO_TRADE_BIND_ON_ACQUIRE' },
  { bit: 7, name: 'CAN_TRADE_BIND_ON_ACQUIRE' },
  { bit: 8, name: 'CAN_ONLY_ROLL_GREED - Makes need roll for this item disabled' },
  { bit: 9, name: 'CASTER_WEAPON' },
  { bit: 10, name: 'DELETE_ON_LOGIN' },
  { bit: 11, name: 'INTERNAL_ITEM' },
  { bit: 12, name: 'NO_VENDOR_VALUE' },
  { bit: 13, name: 'SHOW_BEFORE_DISCOVERED' },
  { bit: 14, name: 'OVERRIDE_GOLD_COST' },
  { bit: 15, name: 'IGNORE_DEFAULT_RATED_BG_RESTRICTIONS' },
  { bit: 16, name: 'NOT_USABLE_IN_RATED_BG' },
  { bit: 17, name: 'BNET_ACCOUNT_TRADE_OK' },
  { bit: 18, name: 'CONFIRM_BEFORE_USE' },
  { bit: 19, name: 'REEVALUATE_BONDING_ON_TRANSFORM' },
  { bit: 20, name: 'NO_TRANSFORM_ON_CHARGE_DEPLETION' },
  { bit: 21, name: 'NO_ALTER_ITEM_VISUAL' },
  { bit: 22, name: 'NO_SOURCE_FOR_ITEM_VISUAL' },
  { bit: 23, name: 'IGNORE_QUALITY_FOR_ITEM_VISUAL_SOURCE' },
  { bit: 24, name: 'NO_DURABILITY' },
  { bit: 25, name: 'ROLE_TANK' },
  { bit: 26, name: 'ROLE_HEALER' },
  { bit: 27, name: 'ROLE_DAMAGE' },
  { bit: 28, name: 'CAN_DROP_IN_CHALLENGE_MODE' },
  { bit: 29, name: 'NEVER_STACK_IN_LOOT_UI' },
  { bit: 30, name: 'DISENCHANT_TO_LOOT_TABLE' },
  { bit: 31, name: 'USED_IN_A_TRADESKILL' },
];
