import { Flag } from '@keira/shared/constants';

export const PHASE_MASK: Flag[] = [
  { bit: 0, name: 'Phase 0' },
  { bit: 1, name: 'Phase 1' },
  { bit: 2, name: 'Phase 2' },
  { bit: 3, name: 'Phase 3' },
  { bit: 4, name: 'Phase 4' },
  { bit: 5, name: 'Phase 5' },
  { bit: 6, name: 'Phase 6' },
  { bit: 7, name: 'Phase 7' },
  { bit: 8, name: 'Phase 8' },
  { bit: 9, name: 'Phase 9' },
  { bit: 10, name: 'Phase 10' },
  { bit: 11, name: 'Phase 11' },
  { bit: 12, name: 'Phase 12' },
  { bit: 13, name: 'Phase 13' },
  { bit: 14, name: 'Phase 14' },
  { bit: 15, name: 'Phase 15' },
  { bit: 16, name: 'Phase 16' },
  { bit: 17, name: 'Phase 17' },
  { bit: 18, name: 'Phase 18' },
  { bit: 19, name: 'Phase 19' },
  { bit: 20, name: 'Phase 20' },
  { bit: 21, name: 'Phase 21' },
  { bit: 22, name: 'Phase 22' },
  { bit: 23, name: 'Phase 23' },
  { bit: 24, name: 'Phase 24' },
  { bit: 25, name: 'Phase 25' },
  { bit: 26, name: 'Phase 26' },
  { bit: 27, name: 'Phase 27' },
  { bit: 28, name: 'Phase 28' },
  { bit: 29, name: 'Phase 29' },
  { bit: 30, name: 'Phase 30' },
  { bit: 31, name: 'Phase 31' },
  { bit: 32, name: 'Phase 32' },
];
