export const SPELL_DBC_SPELL_EFFECT_FIELDS = [
  'SpellClassMask',
  'EffectChainAmplitude',
  'Effect',
  'EffectDieSides',
  'EffectRealPointsPerLevel',
  'EffectBasePoints',
  'EffectMechanic',
  'ImplicitTargetA',
  'ImplicitTargetB',
  'EffectRadiusIndex',
  'EffectAura',
  'EffectAuraPeriod',
  'EffectMultipleValue',
  'EffectChainTargets',
  'EffectItemType',
  'EffectMiscValue',
  'EffectMiscValueB',
  'EffectTriggerSpell',
  'EffectPointsPerCombo',
  'EffectSpellClassMaskA',
  'EffectSpellClassMaskB',
  'EffectSpellClassMaskC',
  'EffectBonusMultiplier',
] as const;
export type SpellDbcSpellEffectFieldPrefix = typeof SPELL_DBC_SPELL_EFFECT_FIELDS[number];
