import { TableRow } from './general';
import { getEnumKeys } from '../utils/helpers';
import { CONDITION_SOURCE_TYPES } from './conditions.type';

export const SAI_TABLE = 'smart_scripts';

export const SAI_ID_FIELDS = [
  'entryorguid',
  'source_type',
];
export const SAI_ID_2 = 'id';
export const SAI_SEARCH_FIELDS = SAI_ID_FIELDS;

export enum SAI_SEARCH_TYPES {
  SAI_TYPE_CREATURE,
  SAI_TYPE_GAMEOBJECT,
  SAI_TYPE_AREATRIGGER,
  SAI_TYPE_TIMED_ACTIONLIST = 9,
}
export const SAI_SEARCH_TYPES_KEYS = getEnumKeys(SAI_SEARCH_TYPES);

export class SmartScripts extends TableRow {
  entryorguid: number = 0;
  source_type: number = 0;
  id: number = 0;
  link: number = 0;
  event_type: number = 0;
  event_phase_mask: number = 0;
  event_chance: number = 100;
  event_flags: number = 0;
  event_param1: number = 0;
  event_param2: number = 0;
  event_param3: number = 0;
  event_param4: number = 0;
  event_param5: number = 0;
  action_type: number = 0;
  action_param1: number = 0;
  action_param2: number = 0;
  action_param3: number = 0;
  action_param4: number = 0;
  action_param5: number = 0;
  action_param6: number = 0;
  target_type: number = 0;
  target_param1: number = 0;
  target_param2: number = 0;
  target_param3: number = 0;
  target_param4: number = 0;
  target_x: number = 0;
  target_y: number = 0;
  target_z: number = 0;
  target_o: number = 0;
  comment: string = '';
}

export enum SAI_EVENTS {
  UPDATE_IC                = 0,
  UPDATE_OOC               = 1,
  HEALTH_PCT               = 2,
  MANA_PCT                 = 3,
  AGGRO                    = 4,
  KILL                     = 5,
  DEATH                    = 6,
  EVADE                    = 7,
  SPELLHIT                 = 8,
  RANGE                    = 9,
  OOC_LOS                  = 10,
  RESPAWN                  = 11,
  TARGET_HEALTH_PCT        = 12,
  VICTIM_CASTING           = 13,
  FRIENDLY_HEALTH          = 14,
  FRIENDLY_IS_CC           = 15,
  FRIENDLY_MISSING_BUFF    = 16,
  SUMMONED_UNIT            = 17,
  TARGET_MANA_PCT          = 18,
  ACCEPTED_QUEST           = 19,
  REWARD_QUEST             = 20,
  REACHED_HOME             = 21,
  RECEIVE_EMOTE            = 22,
  HAS_AURA                 = 23,
  TARGET_BUFFED            = 24,
  RESET                    = 25,
  IC_LOS                   = 26,
  PASSENGER_BOARDED        = 27,
  PASSENGER_REMOVED        = 28,
  CHARMED                  = 29,
  CHARMED_TARGET           = 30,
  SPELLHIT_TARGET          = 31,
  DAMAGED                  = 32,
  DAMAGED_TARGET           = 33,
  MOVEMENTINFORM           = 34,
  SUMMON_DESPAWNED         = 35,
  CORPSE_REMOVED           = 36,
  AI_INIT                  = 37,
  DATA_SET                 = 38,
  WAYPOINT_START           = 39,
  WAYPOINT_REACHED         = 40,
  TRANSPORT_ADDPLAYER      = 41,
  TRANSPORT_ADDCREATURE    = 42,
  TRANSPORT_REMOVE_PLAYER  = 43,
  TRANSPORT_RELOCATE       = 44,
  INSTANCE_PLAYER_ENTER    = 45,
  AREATRIGGER_ONTRIGGER    = 46,
  QUEST_ACCEPTED           = 47,
  QUEST_OBJ_COPLETETION    = 48,
  QUEST_COMPLETION         = 49,
  QUEST_REWARDED           = 50,
  QUEST_FAIL               = 51,
  TEXT_OVER                = 52,
  RECEIVE_HEAL             = 53,
  JUST_SUMMONED            = 54,
  WAYPOINT_PAUSED          = 55,
  WAYPOINT_RESUMED         = 56,
  WAYPOINT_STOPPED         = 57,
  WAYPOINT_ENDED           = 58,
  TIMED_EVENT_TRIGGERED    = 59,
  UPDATE                   = 60,
  LINK                     = 61,
  GOSSIP_SELECT            = 62,
  JUST_CREATED             = 63,
  GOSSIP_HELLO             = 64,
  FOLLOW_COMPLETED         = 65,
  // UNUSED_66                = 66, // unused
  IS_BEHIND_TARGET         = 67,
  GAME_EVENT_START         = 68,
  GAME_EVENT_END           = 69,
  GO_STATE_CHANGED         = 70,
  GO_EVENT_INFORM          = 71,
  ACTION_DONE              = 72,
  ON_SPELLCLICK            = 73,
  FRIENDLY_HEALTH_PCT      = 74,
  DISTANCE_CREATURE        = 75,
  DISTANCE_GAMEOBJECT      = 76,
  COUNTER_SET              = 77,
}
export const SAI_EVENTS_KEYS = getEnumKeys(SAI_EVENTS);

export enum SAI_ACTIONS {
  NONE                               = 0,
  TALK                               = 1,
  SET_FACTION                        = 2,
  MORPH_TO_ENTRY_OR_MODEL            = 3,
  SOUND                              = 4,
  PLAY_EMOTE                         = 5,
  FAIL_QUEST                         = 6,
  OFFER_QUEST                        = 7,
  SET_REACT_STATE                    = 8,
  ACTIVATE_GOBJECT                   = 9,
  RANDOM_EMOTE                       = 10,
  CAST                               = 11,
  SUMMON_CREATURE                    = 12,
  THREAT_SINGLE_PCT                  = 13,
  THREAT_ALL_PCT                     = 14,
  CALL_AREAEXPLOREDOREVENTHAPPENS    = 15,
  RESERVED_16                        = 16,
  SET_EMOTE_STATE                    = 17,
  SET_UNIT_FLAG                      = 18,
  REMOVE_UNIT_FLAG                   = 19,
  AUTO_ATTACK                        = 20,
  ALLOW_COMBAT_MOVEMENT              = 21,
  SET_EVENT_PHASE                    = 22,
  INC_EVENT_PHASE                    = 23,
  EVADE                              = 24,
  FLEE_FOR_ASSIST                    = 25,
  CALL_GROUPEVENTHAPPENS             = 26,
  COMBAT_STOP                        = 27,
  REMOVEAURASFROMSPELL               = 28,
  FOLLOW                             = 29,
  RANDOM_PHASE                       = 30,
  RANDOM_PHASE_RANGE                 = 31,
  RESET_GOBJECT                      = 32,
  CALL_KILLEDMONSTER                 = 33,
  SET_INST_DATA                      = 34,
  SET_INST_DATA64                    = 35,
  UPDATE_TEMPLATE                    = 36,
  DIE                                = 37,
  SET_IN_COMBAT_WITH_ZONE            = 38,
  CALL_FOR_HELP                      = 39,
  SET_SHEATH                         = 40,
  FORCE_DESPAWN                      = 41,
  SET_INVINCIBILITY_HP_LEVEL         = 42,
  MOUNT_TO_ENTRY_OR_MODEL            = 43,
  SET_INGAME_PHASE_MASK              = 44,
  SET_DATA                           = 45,
  MOVE_FORWARD                       = 46,
  SET_VISIBILITY                     = 47,
  SET_ACTIVE                         = 48,
  ATTACK_START                       = 49,
  SUMMON_GO                          = 50,
  KILL_UNIT                          = 51,
  ACTIVATE_TAXI                      = 52,
  WP_START                           = 53,
  WP_PAUSE                           = 54,
  WP_STOP                            = 55,
  ADD_ITEM                           = 56,
  REMOVE_ITEM                        = 57,
  INSTALL_AI_TEMPLATE                = 58,
  SET_RUN                            = 59,
  SET_FLY                            = 60,
  SET_SWIM                           = 61,
  TELEPORT                           = 62,
  SET_COUNTER                        = 63,
  STORE_TARGET_LIST                  = 64,
  WP_RESUME                          = 65,
  SET_ORIENTATION                    = 66,
  CREATE_TIMED_EVENT                 = 67,
  PLAYMOVIE                          = 68,
  MOVE_TO_POS                        = 69,
  RESPAWN_TARGET                     = 70,
  EQUIP                              = 71,
  CLOSE_GOSSIP                       = 72,
  TRIGGER_TIMED_EVENT                = 73,
  REMOVE_TIMED_EVENT                 = 74,
  ADD_AURA                           = 75,
  OVERRIDE_SCRIPT_BASE_OBJECT        = 76,
  RESET_SCRIPT_BASE_OBJECT           = 77,
  CALL_SCRIPT_RESET                  = 78,
  SET_RANGED_MOVEMENT                = 79,
  CALL_TIMED_ACTIONLIST              = 80,
  SET_NPC_FLAG                       = 81,
  ADD_NPC_FLAG                       = 82,
  REMOVE_NPC_FLAG                    = 83,
  SIMPLE_TALK                        = 84,
  INVOKER_CAST                       = 85,
  CROSS_CAST                         = 86,
  CALL_RANDOM_TIMED_ACTIONLIST       = 87,
  CALL_RANDOM_RANGE_TIMED_ACTIONLIST = 88,
  RANDOM_MOVE                        = 89,
  SET_UNIT_FIELD_BYTES_1             = 90,
  REMOVE_UNIT_FIELD_BYTES_1          = 91,
  INTERRUPT_SPELL                    = 92,
  SEND_GO_CUSTOM_ANIM                = 93,
  SET_DYNAMIC_FLAG                   = 94,
  ADD_DYNAMIC_FLAG                   = 95,
  REMOVE_DYNAMIC_FLAG                = 96,
  JUMP_TO_POS                        = 97,
  SEND_GOSSIP_MENU                   = 98,
  GO_SET_LOOT_STATE                  = 99,
  SEND_TARGET_TO_TARGET              = 100,
  SET_HOME_POS                       = 101,
  SET_HEALTH_REGEN                   = 102,
  SET_ROOT                           = 103,
  SET_GO_FLAG                        = 104,
  ADD_GO_FLAG                        = 105,
  REMOVE_GO_FLAG                     = 106,
  SUMMON_CREATURE_GROUP              = 107,
  SET_POWER                          = 108,
  ADD_POWER                          = 109,
  REMOVE_POWER                       = 110,
  GAME_EVENT_STOP                    = 111,
  GAME_EVENT_START                   = 112,
  START_CLOSEST_WAYPOINT             = 113,
  RISE_UP                            = 114,
  RANDOM_SOUND                       = 115,
  // SET_CORPSE_DELAY                   = 116, //  NOT SUPPORTED YET
  // DISABLE_EVADE                      = 117, //  NOT SUPPORTED YET
  // GO_SET_GO_STATE                    = 118, //  NOT SUPPORTED YET
  // SET_CAN_FLY                        = 119, //  NOT SUPPORTED YET
  // REMOVE_AURAS_BY_TYPE               = 120, //  NOT SUPPORTED YET
  SET_SIGHT_DIST                     = 121,
  FLEE                               = 122,
  ADD_THREAT                         = 123,
  LOAD_EQUIPMENT                     = 124,
  TRIGGER_RANDOM_TIMED_EVENT         = 125,
  REMOVE_ALL_GAMEOBJECTS             = 126,
  // REMOVE_MOVEMENT                    = 127, // NOT SUPPORTED YET
  // PLAY_ANIMKIT                       = 128, // don't use on 3.3.5a
  // SCENE_PLAY                         = 129, // don't use on 3.3.5a
  // SCENE_CANCEL                       = 130, // don't use on 3.3.5a
  // SPAWN_SPAWNGROUP                   = 131, // NOT SUPPORTED YET
  // DESPAWN_SPAWNGROUP                 = 132, // NOT SUPPORTED YET
  // RESPAWN_BY_SPAWNID                 = 133, // NOT SUPPORTED YET
  // INVOKER_CAST                       = 134, // name conflicts

  // AC-only SmartActions:
  MOVE_TO_POS_TARGET                 = 201,
  SET_GO_STATE                       = 202,
  EXIT_VEHICLE                       = 203,
  SET_UNIT_MOVEMENT_FLAGS            = 204,
  SET_COMBAT_DISTANCE                = 205,
  SET_CASTER_COMBAT_DIST             = 206,
  SET_HOVER                          = 207,
  ADD_IMMUNITY                       = 208,
  REMOVE_IMMUNITY                    = 209,
  FALL                               = 210,
  SET_EVENT_FLAG_RESET               = 211,
  STOP_MOTION                        = 212,
  NO_ENVIRONMENT_UPDATE              = 213,
  ZONE_UNDER_ATTACK                  = 214,
  LOAD_GRID                          = 215,
  MUSIC                              = 216,
  RANDOM_MUSIC                       = 217,
}
export const SAI_ACTIONS_KEYS = getEnumKeys(SAI_ACTIONS);

export enum SAI_TARGETS {
  NONE                           = 0,
  SELF                           = 1,
  VICTIM                         = 2,
  HOSTILE_SECOND_AGGRO           = 3,
  HOSTILE_LAST_AGGRO             = 4,
  HOSTILE_RANDOM                 = 5,
  HOSTILE_RANDOM_NOT_TOP         = 6,
  ACTION_INVOKER                 = 7,
  POSITION                       = 8,
  CREATURE_RANGE                 = 9,
  CREATURE_GUID                  = 10,
  CREATURE_DISTANCE              = 11,
  STORED                         = 12,
  GAMEOBJECT_RANGE               = 13,
  GAMEOBJECT_GUID                = 14,
  GAMEOBJECT_DISTANCE            = 15,
  INVOKER_PARTY                  = 16,
  PLAYER_RANGE                   = 17,
  PLAYER_DISTANCE                = 18,
  CLOSEST_CREATURE               = 19,
  CLOSEST_GAMEOBJECT             = 20,
  CLOSEST_PLAYER                 = 21,
  ACTION_INVOKER_VEHICLE         = 22,
  OWNER_OR_SUMMONER              = 23,
  THREAT_LIST                    = 24,
  CLOSEST_ENEMY                  = 25,
  CLOSEST_FRIENDLY               = 26,
  // LOOT_RECIPIENTS                = 27,   // NOT SUPPORTED YET
  FARTHEST                       = 28,
  // VEHICLE_PASSENGER              = 29,   // NOT SUPPORTED YET
}
export const SAI_TARGETS_KEYS = getEnumKeys(SAI_TARGETS);

export const SAI_EVENT_TOOLTIPS = [];
SAI_EVENT_TOOLTIPS[SAI_EVENTS.UPDATE_IC]  = 'While in combat. Parameters represent a timer: 1000,2000,4000,4000 will call this event_type randomly between 1 and 2 seconds and repeat this every 4 seconds';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.UPDATE_OOC]  = 'While out of combat. Parameters represent a timer: 1000,2000,4000,4000 will call this event_type randomly between 1 and 2 seconds and repeat this every 4 seconds';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.HEALTH_PCT]  = 'At health percentage. First and second parameters function as min-max health percentage values, so if they are  50,80, the event will be called when the source is between 50% and 80% health. The last two parameters are repeat timers in milliseconds.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.MANA_PCT]  = 'At mana percentage. First and second parameters function as min-max mana percentage values, so if they are  50,80, the event will be called when the source is between 50% and 80% mana. The last two parameters are repeat timers in milliseconds.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.AGGRO]  = 'When the creature enters combat';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.KILL]  = 'When the creature killed something';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.DEATH]  = 'When the creature just died';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.EVADE]  = 'When the creature evades out of combat';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.SPELLHIT]  = 'On creature struck by a spell id';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.RANGE]  = 'When the creature is within a certain range of our target type';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.OOC_LOS] = 'When the creature detects movement of an unit that is within line of sight while the creature is out of combat. This should be used when attempting to trigger an action when a player or so moves within a distance of some place/trigger.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.RESPAWN] = 'When the creature or gameobject respawns or spawns';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TARGET_HEALTH_PCT] = 'When the target of the creature is at a certain health percentage';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.VICTIM_CASTING] = 'When the target of the creature is casting a spell. Leaving the third parameter at 0 will mean any spell the target casts will trigger this event.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.FRIENDLY_HEALTH] = 'When a friendly unit within a certain range reaches a certain amount of health (NOT PERCENTAGE!). If you are looking for percentage, use event type 74.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.FRIENDLY_IS_CC] = 'When a friendly unit within a certain range is under the effect of a crowd control spell';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.FRIENDLY_MISSING_BUFF] = 'When a friendly unit within a certain range is missing or having an aura/spell on them. If the first parameter is the spellid in a negative format, it will mean the event is triggered when a friendly unit within a certain range HAS a buff.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.SUMMONED_UNIT] = 'When we summoned a creature with a certain entry. First parameter is the creature entry and if it\'s left at 0 it means we trigger this for any creature.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TARGET_MANA_PCT] = 'When the target of the creature is at a certain mana percentage';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.ACCEPTED_QUEST] = 'When the creature successfully offered a quest to a player';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.REWARD_QUEST] = 'When the creature successfully rewarded a quest of a player';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.REACHED_HOME] = 'When the creature reached its home position';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.RECEIVE_EMOTE] = 'When the creature receives an emote';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.HAS_AURA] = 'When the creature is missing or having an aura/spell on them. If the first parameter is the spellid in a negative format, it will mean the event is triggered when a friendly unit within a certain range is MISSING a buff.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TARGET_BUFFED] = 'When the creature\'s target is missing or having an aura/spell on them. If the first parameter is the spellid in a negative format, it will mean the event is triggered when a friendly unit within a certain range is MISSING a buff.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.RESET] = 'When the creature resets (evades, respawns, spawns or resets out of combat)';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.IC_LOS] = 'When the creature detects movement of an unit that is within line of sight while the creature is in combat. This should be used when attempting to trigger an action when a player or so moves within a distance of some place/trigger.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.PASSENGER_BOARDED] = 'When a passenger is boarded';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.PASSENGER_REMOVED] = 'When a passenger is removed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.CHARMED] = 'On creature charmed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.CHARMED_TARGET] = 'On target charmed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.SPELLHIT_TARGET] = 'On target spellhit by a spell';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.DAMAGED] = 'On creature damaged for a certain amount';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.DAMAGED_TARGET] = 'On target damaged for a certain amount';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.MOVEMENTINFORM] = 'On movement inform. Useful when for example you want your creature to do something after it moving to a certain spot by using SMART_ACTION_MOVE_TO.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.SUMMON_DESPAWNED] = 'On summoned unit despawned';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.CORPSE_REMOVED] = 'On creature corpse removal';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.AI_INIT] = 'On AI initialization, so when the creature spawns (not when it respawns, resets or evades!)';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.DATA_SET] = 'On data set, called after SMART_ACTION_SET_DATA is called to this source with a certain field and a certain value.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.WAYPOINT_START] = 'On waypoint started';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.WAYPOINT_REACHED] = 'On waypoint reached';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TRANSPORT_ADDPLAYER] = '';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TRANSPORT_ADDCREATURE] = '';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TRANSPORT_REMOVE_PLAYER] = '';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TRANSPORT_RELOCATE] = '';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.INSTANCE_PLAYER_ENTER] = '';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.AREATRIGGER_ONTRIGGER] = 'On areatrigger reached by a player';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.QUEST_ACCEPTED] = 'On target quest accepted';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.QUEST_OBJ_COPLETETION] = 'On target quest objective completed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.QUEST_COMPLETION] = 'On target quest completed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.QUEST_REWARDED] = 'On target quest rewarded';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.QUEST_FAIL] = 'On target quest failed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TEXT_OVER] = 'When a creature says something it shows a balloon for a few seconds. This event is triggered after the balloon fades and thus the text \'finishes\'.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.RECEIVE_HEAL] = 'On creature received a certain heal amount';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.JUST_SUMMONED] = 'Called when the creature or gameobject has just been summoned';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.WAYPOINT_PAUSED] = 'On waypoint paused';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.WAYPOINT_RESUMED] = 'On waypoint resumed';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.WAYPOINT_STOPPED] = 'On waypoint stopped';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.WAYPOINT_ENDED] = 'On waypoint ended';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.TIMED_EVENT_TRIGGERED] = 'Called when a timed event called by the action CREATE_TIMED_EVENT is triggered';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.UPDATE] = 'On update, should be used as a timer. Basically functions like both UPDATE_IC and UPDATE_OOC in one.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.LINK] = 'On link';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.GOSSIP_SELECT] = 'Called on gossip option selected. Imagine you have four gossip items under the menu id 5 and their id\'s are 0, 1 and 2. If you now call this event with first parameter \'5\' and second parameter \'1\', it will be called when the second gossip option is selected. Tables gossip_menu_option and gossip_menu.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.JUST_CREATED] = 'On gameobject just created (so when it spawns for the first time)';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.GOSSIP_HELLO] = 'On gossip menu opened. Also called for gameobjects that just got \'opened\' by a player.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.FOLLOW_COMPLETED] = 'On follow completed/finished';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.IS_BEHIND_TARGET] = 'On behind target within a certain cooldown time';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.GAME_EVENT_START] = 'On game event entry just started';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.GAME_EVENT_END] = 'On game event entry just ended';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.GO_STATE_CHANGED] = 'On gameobject state changed.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.GO_EVENT_INFORM] = 'Called when the gameobject becomes the target of an event happening. This is called in cases like a building is damaged/destroyed/rebuild, a goober is used, etc.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.ACTION_DONE] = 'Called on a certain action id \'done\'. Those can only be called from core scripts (SmartAI::DoAction).';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.ON_SPELLCLICK] = 'On unit spellclick. For more information on what spellclicks are, take a look at the wiki and search for the table \'npc_spellclick_spells\' (world database).';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.FRIENDLY_HEALTH_PCT] = 'When a friendly unit within a certain range reaches a certain health percentage (so NOT flat health!). If you are looking for a flat modifier, use event type 14.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.DISTANCE_CREATURE] = 'Event triggered when a creature with a specific guid or entry coems within a given distance (in yards) of the source.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.DISTANCE_GAMEOBJECT] = 'Event triggered when a gameobject with a specific guid or entry coems within a given distance (in yards) of the source.';
SAI_EVENT_TOOLTIPS[SAI_EVENTS.COUNTER_SET] = 'If the value of specified counterID (param1) is equal to a specified value';

export const SAI_ACTION_TOOLTIPS = [];
// TODO

export const SAI_TARGET_TOOLTIPS = [];
// TODO
