import { Flag } from '../../types/general';

export const FLAGS_EXTRA: Flag[] = [
  { bit: 0,  name: `INSTANCE_BIND - creature kill bind instance with killer and killer's group` },
  { bit: 1,  name: `CIVILIAN - not aggro (ignore faction/reputation hostility)` },
  { bit: 2,  name: `NO_PARRY - creature can't parry` },
  { bit: 3,  name: `NO_PARRY_HASTEN - creature can't counter-attack at parry` },
  { bit: 4,  name: `NO_BLOCK - creature can't block` },
  { bit: 5,  name: `NO_CRUSH - creature can't do crush attacks` },
  { bit: 6,  name: `NO_XP_AT_KILL - creature kill not provide XP` },
  { bit: 7,  name: `TRIGGER - trigger creature` },
  { bit: 8,  name: `NO_TAUNT - creature is immune to taunt auras and effect attack me` },
  { bit: 9,  name: `UNKNOWN` },
  { bit: 10, name: `UNKNOWN` },
  { bit: 11, name: `UNKNOWN` },
  { bit: 12, name: `UNKNOWN` },
  { bit: 13, name: `UNKNOWN` },
  { bit: 14, name: `WORLDEVENT - custom flag for world event creatures (left room for merging)` },
  { bit: 15, name: `GUARD - Creature is guard` },
  { bit: 16, name: `UNKNOWN` },
  { bit: 17, name: `NO_CRIT - creature can't do critical strikes` },
  { bit: 18, name: `NO_SKILLGAIN - creature won't increase weapon skills` },
  { bit: 19, name: `TAUNT_DIMINISH - Taunt is a subject to diminishing returns on this creature` },
  { bit: 20, name: `ALL_DIMINISH - Creature is subject to all diminishing returns as player are` },
  { bit: 21, name: `KNOCKBACK_IMMUNE - set mostly for dungeon bosses and their summons` },
  { bit: 22, name: `AVOID_AOE - ignored by aoe attacks (for icc blood prince council npc - Dark Nucleus)` },
  { bit: 23, name: `NO_DODGE - target cannot dodge` },
  { bit: 24, name: `DUNGEON_BOSS - creature is a dungeon boss (SET DYNAMICALLY, DO NOT ADD IN DB)` },
  { bit: 25, name: `IGNORE_PATHFINDING - creature ignore pathfinding` },
];
