import { Flag } from '@keira/acore-world-model';

export const MECHANIC_IMMUNE_MASK: Flag[] = [
  { bit: 0, name: 'CHARM' },
  { bit: 1, name: 'DISORIENTED' },
  { bit: 2, name: 'DISARM' },
  { bit: 3, name: 'DISTRACT' },
  { bit: 4, name: 'FEAR' },
  { bit: 5, name: 'GRIP - Death Grip and similar effects' },
  { bit: 6, name: 'ROOT' },
  { bit: 7, name: 'SLOW_ATTACK' },
  { bit: 8, name: 'SILENCE' },
  { bit: 9, name: 'SLEEP' },
  { bit: 10, name: 'SNARE' },
  { bit: 11, name: 'STUN' },
  { bit: 12, name: 'FREEZE' },
  { bit: 13, name: 'KNOCKOUT - Incapacitate effects such as Repentance (Paladin)' },
  { bit: 14, name: 'BLEED' },
  { bit: 15, name: 'BANDAGE - Healing' },
  { bit: 16, name: 'POLYMORPH' },
  { bit: 17, name: 'BANISH' },
  { bit: 18, name: 'SHIELD' },
  { bit: 19, name: 'SHACKLE - Shackle Undead only' },
  { bit: 20, name: 'MOUNT - Any effect that summons a mount' },
  { bit: 21, name: 'INFECTED - e.g. Frost Fever, Blood Plague etc..' },
  { bit: 22, name: 'TURN - e.g. Turn Evil' },
  { bit: 23, name: 'HORROR - e.g. Death Coil (Warlock)' },
  { bit: 24, name: 'INVULNERABILITY - Forbearance, Nether Protection, Diplomatic Immunity only' },
  { bit: 25, name: 'INTERRUPT' },
  { bit: 26, name: 'DAZE' },
  { bit: 27, name: 'DISCOVERY - Any Create Item effect' },
  { bit: 28, name: 'IMMUNE_SHIELD - e.g. Divine Shield, Ice Block, Hand of Protection' },
  { bit: 29, name: 'SAPPED' },
  { bit: 30, name: 'ENRAGED' },
];
