import { Option } from '../../types/general';

export const FACTIONS: Option[] = [
  { value: 0,    name: `NONE` },
  { value: 1,    name: `PLAYER, Human` },
  { value: 2,    name: `PLAYER, Orc` },
  { value: 3,    name: `PLAYER, Dwarf` },
  { value: 4,    name: `PLAYER, Night Elf` },
  { value: 5,    name: `PLAYER, Undead` },
  { value: 6,    name: `PLAYER, Tauren ` },
  { value: 7,    name: `Creature` },
  { value: 10,   name: `Escortee` },
  { value: 11,   name: `Stormwind ` },
  { value: 12,   name: `Stormwind` },
  { value: 14,   name: `Monster` },
  { value: 15,   name: `Creature` },
  { value: 16,   name: `Monster` },
  { value: 17,   name: `Defias Brotherhood` },
  { value: 18,   name: `Murloc` },
  { value: 19,   name: `Gnoll - Redridge` },
  { value: 20,   name: `Gnoll - Riverpaw` },
  { value: 21,   name: `Undead, Scourge` },
  { value: 22,   name: `Beast - Spider` },
  { value: 23,   name: `Gnomeregan Exiles` },
  { value: 24,   name: `Worgen` },
  { value: 25,   name: `Kobold` },
  { value: 26,   name: `Kobold` },
  { value: 27,   name: `Defias Brotherhood` },
  { value: 28,   name: `Troll, Bloodscalp` },
  { value: 29,   name: `Orgrimmar` },
  { value: 30,   name: `Troll, Skullsplitter` },
  { value: 31,   name: `Prey` },
  { value: 32,   name: `Beast - Wolf` },
  { value: 33,   name: `Escortee` },
  { value: 34,   name: `Defias Brotherhood` },
  { value: 35,   name: `Friendly` },
  { value: 36,   name: `Trogg` },
  { value: 37,   name: `Troll, Frostmane` },
  { value: 38,   name: `Beast - Wolf` },
  { value: 39,   name: `Gnoll-Shadowhide` },
  { value: 40,   name: `Orc,Blackrock` },
  { value: 41,   name: `Villian` },
  { value: 42,   name: `Victim` },
  { value: 43,   name: `Villian` },
  { value: 44,   name: `Beast-Bear` },
  { value: 45,   name: `Ogre` },
  { value: 46,   name: `Kurzen's Mercenaries` },
  { value: 47,   name: `Venture Company` },
  { value: 48,   name: `Beast-Raptor` },
  { value: 49,   name: `Basilisk` },
  { value: 50,   name: `Dragonflight,Green` },
  { value: 51,   name: `Lost Ones` },
  { value: 52,   name: `Gizlock's Dummy` },
  { value: 53,   name: `Human,Night Watch` },
  { value: 54,   name: `Dark Iron Dwarves` },
  { value: 55,   name: `Ironforge` },
  { value: 56,   name: `Human,Night Watch` },
  { value: 57,   name: `Ironforge` },
  { value: 58,   name: `Creature` },
  { value: 59,   name: `Trogg` },
  { value: 60,   name: `Dragonflight,Red` },
  { value: 61,   name: `Gnoll-Mosshide` },
  { value: 62,   name: `Orc,Dragonmaw` },
  { value: 63,   name: `Gnome-Leper` },
  { value: 64,   name: `Gnomeregan Exiles` },
  { value: 65,   name: `Orgrimmar` },
  { value: 66,   name: `Leopard` },
  { value: 67,   name: `Scarlet Crusade` },
  { value: 68,   name: `Undercity` },
  { value: 69,   name: `Ratchet` },
  { value: 70,   name: `Gnoll-Rothide` },
  { value: 71,   name: `Undercity` },
  { value: 72,   name: `Beast-Gorilla` },
  { value: 73,   name: `Beast-Carrion Bird` },
  { value: 74,   name: `Naga` },
  { value: 76,   name: `Dalaran` },
  { value: 77,   name: `Forlorn Spirit` },
  { value: 78,   name: `Darkhowl` },
  { value: 79,   name: `Darnassus` },
  { value: 80,   name: `Darnassus` },
  { value: 81,   name: `Grell` },
  { value: 82,   name: `Furbolg` },
  { value: 83,   name: `Horde Generic` },
  { value: 84,   name: `Alliance Generic` },
  { value: 85,   name: `Orgrimmar` },
  { value: 86,   name: `Gizlock's Charm` },
  { value: 87,   name: `Syndicate` },
  { value: 88,   name: `Hillsbrad Militia` },
  { value: 89,   name: `Scarlet Crusade` },
  { value: 90,   name: `Demon` },
  { value: 91,   name: `Elemental` },
  { value: 92,   name: `Spirit` },
  { value: 93,   name: `Monster` },
  { value: 94,   name: `Treasure` },
  { value: 95,   name: `Gnoll-Mudsnout` },
  { value: 96,   name: `HIllsbrad,Southshore Mayor` },
  { value: 97,   name: `Syndicate` },
  { value: 98,   name: `Undercity` },
  { value: 99,   name: `Victim` },
  { value: 100,  name: `Treasure` },
  { value: 101,  name: `Treasure` },
  { value: 102,  name: `Treasure` },
  { value: 103,  name: `Dragonflight,Black` },
  { value: 104,  name: `Thunder Bluff` },
  { value: 105,  name: `Thunder Bluff` },
  { value: 106,  name: `Horde Generic` },
  { value: 107,  name: `Troll,Frostmane` },
  { value: 108,  name: `Syndicate` },
  { value: 109,  name: `Quilboar,Razormane 2` },
  { value: 110,  name: `Quilboar,Razormane 2` },
  { value: 111,  name: `Quilboar,Bristleback` },
  { value: 112,  name: `Quilboar,Bristleback` },
  { value: 113,  name: `Escortee` },
  { value: 114,  name: `Treasure` },
  { value: 115,  name: `PLAYER,Gnome` },
  { value: 116,  name: `PLAYER,Troll` },
  { value: 118,  name: `Undercity` },
  { value: 119,  name: `Bloodsail Buccaneers` },
  { value: 120,  name: `Booty Bay` },
  { value: 121,  name: `Booty Bay` },
  { value: 122,  name: `Ironforge` },
  { value: 123,  name: `Stormwind` },
  { value: 124,  name: `Darnassus` },
  { value: 125,  name: `Orgrimmar` },
  { value: 126,  name: `Darkspear Trolls` },
  { value: 127,  name: `Villian` },
  { value: 128,  name: `Blackfathom` },
  { value: 129,  name: `Makrura` },
  { value: 130,  name: `Centaur,Kolkar` },
  { value: 131,  name: `Centaur,Galak` },
  { value: 132,  name: `Gelkis Clan Centaur` },
  { value: 133,  name: `Magram Clan Centaur` },
  { value: 134,  name: `Maraudine` },
  { value: 148,  name: `Monster` },
  { value: 149,  name: `Theramore` },
  { value: 150,  name: `Theramore` },
  { value: 151,  name: `Theramore` },
  { value: 152,  name: `Quilboar,Razorfen` },
  { value: 153,  name: `Quilboar,Razorfen` },
  { value: 154,  name: `Quilboar,Deathshead` },
  { value: 168,  name: `Enemy` },
  { value: 188,  name: `Ambient` },
  { value: 189,  name: `Creature` },
  { value: 190,  name: `Ambient` },
  { value: 208,  name: `Nethergarde Caravan` },
  { value: 209,  name: `Nethergarde Caravan` },
  { value: 210,  name: `Alliance Generic` },
  { value: 230,  name: `Southsea Freebooters` },
  { value: 231,  name: `Escortee` },
  { value: 232,  name: `Escortee` },
  { value: 233,  name: `Undead,Scourge` },
  { value: 250,  name: `Escortee` },
  { value: 270,  name: `Wailing Caverns` },
  { value: 290,  name: `Escortee` },
  { value: 310,  name: `Silithid` },
  { value: 311,  name: `Silithid` },
  { value: 312,  name: `Beast-Spider` },
  { value: 330,  name: `Wailing Caverns` },
  { value: 350,  name: `Blackfathom` },
  { value: 370,  name: `Armies of C'Thun` },
  { value: 371,  name: `Silvermoon Remnant` },
  { value: 390,  name: `Booty Bay` },
  { value: 410,  name: `Basilisk` },
  { value: 411,  name: `Beast-Bat` },
  { value: 412,  name: `The Defilers` },
  { value: 413,  name: `Scorpid` },
  { value: 414,  name: `Timbermaw Hold` },
  { value: 415,  name: `Titan` },
  { value: 416,  name: `Titan` },
  { value: 430,  name: `Taskmaster Fizzule` },
  { value: 450,  name: `Wailing Caverns` },
  { value: 470,  name: `Titan` },
  { value: 471,  name: `Ravenholdt` },
  { value: 472,  name: `Syndicate` },
  { value: 473,  name: `Ravenholdt` },
  { value: 474,  name: `Gadgetzan` },
  { value: 475,  name: `Gadgetzan` },
  { value: 494,  name: `Gnomeregan Bug` },
  { value: 495,  name: `Escortee` },
  { value: 514,  name: `Harpy` },
  { value: 534,  name: `Alliance Generic` },
  { value: 554,  name: `Burning Blade` },
  { value: 574,  name: `Shadowsilk Poacher` },
  { value: 575,  name: `Searing Spider` },
  { value: 594,  name: `Trogg` },
  { value: 614,  name: `Victim` },
  { value: 634,  name: `Monster` },
  { value: 635,  name: `Cenarion Circle` },
  { value: 636,  name: `Timbermaw Hold` },
  { value: 637,  name: `Ratchet` },
  { value: 654,  name: `Troll,Witherbark` },
  { value: 655,  name: `Centaur,Kolkar` },
  { value: 674,  name: `Dark Iron Dwarves` },
  { value: 694,  name: `Alliance Generic` },
  { value: 695,  name: `Hydraxian Waterlords` },
  { value: 714,  name: `Horde Generic` },
  { value: 734,  name: `Dark Iron Dwarves` },
  { value: 735,  name: `Goblin,Dark Iron Bar Patron` },
  { value: 736,  name: `Goblin,Dark Iron Bar Patron` },
  { value: 754,  name: `Dark Iron Dwarves` },
  { value: 774,  name: `Escortee` },
  { value: 775,  name: `Escortee` },
  { value: 776,  name: `Brood of Nozdormu` },
  { value: 777,  name: `Might of Kalimdor` },
  { value: 778,  name: `Giant` },
  { value: 794,  name: `Argent Dawn` },
  { value: 795,  name: `Troll,Vilebranch` },
  { value: 814,  name: `Argent Dawn` },
  { value: 834,  name: `Elemental` },
  { value: 854,  name: `Everlook` },
  { value: 855,  name: `Everlook` },
  { value: 874,  name: `Wintersaber Trainers` },
  { value: 875,  name: `Gnomeregan Exiles` },
  { value: 876,  name: `Darkspear Trolls` },
  { value: 877,  name: `Darkspear Trolls` },
  { value: 894,  name: `Theramore` },
  { value: 914,  name: `Training Dummy` },
  { value: 934,  name: `Furbolg,Uncorrupted` },
  { value: 954,  name: `Demon` },
  { value: 974,  name: `Undead,Scourge` },
  { value: 994,  name: `Cenarion Circle` },
  { value: 995,  name: `Thunder Bluff` },
  { value: 996,  name: `Cenarion Circle` },
  { value: 1014, name: `Shatterspear Trolls` },
  { value: 1015, name: `Shatterspear Trolls` },
  { value: 1034, name: `Horde Generic` },
  { value: 1054, name: `Alliance Generic` },
  { value: 1055, name: `Alliance Generic` },
  { value: 1074, name: `Orgrimmar` },
  { value: 1075, name: `Theramore` },
  { value: 1076, name: `Darnassus` },
  { value: 1077, name: `Theramore` },
  { value: 1078, name: `Stormwind` },
  { value: 1080, name: `Friendly` },
  { value: 1081, name: `Elemental` },
  { value: 1094, name: `Beast-Boar` },
  { value: 1095, name: `Training Dummy` },
  { value: 1096, name: `Theramore` },
  { value: 1097, name: `Darnassus` },
  { value: 1114, name: `Dragonflight,Black-Bait` },
  { value: 1134, name: `Undercity` },
  { value: 1154, name: `Undercity` },
  { value: 1174, name: `Orgrimmar` },
  { value: 1194, name: `Battleground Neutral` },
  { value: 1214, name: `Frostwolf Clan` },
  { value: 1215, name: `Frostwolf Clan` },
  { value: 1216, name: `Stormpike Guard` },
  { value: 1217, name: `Stormpike Guard` },
  { value: 1234, name: `Sulfuron Firelords` },
  { value: 1235, name: `Sulfuron Firelords` },
  { value: 1236, name: `Sulfuron Firelords` },
  { value: 1254, name: `Cenarion Circle` },
  { value: 1274, name: `Creature` },
  { value: 1275, name: `Creature` },
  { value: 1294, name: `Gizlock` },
  { value: 1314, name: `Horde Generic` },
  { value: 1315, name: `Alliance Generic` },
  { value: 1334, name: `Stormpike Guard` },
  { value: 1335, name: `Frostwolf Clan` },
  { value: 1354, name: `Shen'dralar` },
  { value: 1355, name: `Shen'dralar` },
  { value: 1374, name: `Ogre(Captain Kromcrush)` },
  { value: 1375, name: `Treasure` },
  { value: 1394, name: `Dragonflight,Black` },
  { value: 1395, name: `Silithid Attackers` },
  { value: 1414, name: `Spirit Guide-Alliance` },
  { value: 1415, name: `Spirit Guide-Horde` },
  { value: 1434, name: `Jaedenar` },
  { value: 1454, name: `Victim` },
  { value: 1474, name: `Thorium Brotherhood` },
  { value: 1475, name: `Thorium Brotherhood` },
  { value: 1494, name: `Horde Generic` },
  { value: 1495, name: `Horde Generic` },
  { value: 1496, name: `Horde Generic` },
  { value: 1514, name: `Silverwing Sentinels` },
  { value: 1515, name: `Warsong Outriders` },
  { value: 1534, name: `Stormpike Guard` },
  { value: 1554, name: `Frostwolf Clan` },
  { value: 1555, name: `Darkmoon Faire` },
  { value: 1574, name: `Zandalar Tribe` },
  { value: 1575, name: `Stormwind` },
  { value: 1576, name: `Silvermoon Remnant` },
  { value: 1577, name: `The League of Arathor` },
  { value: 1594, name: `Darnassus` },
  { value: 1595, name: `Orgrimmar` },
  { value: 1596, name: `Stormpike Guard` },
  { value: 1597, name: `Frostwolf Clan` },
  { value: 1598, name: `The Defilers` },
  { value: 1599, name: `The League of Arathor` },
  { value: 1600, name: `Darnassus` },
  { value: 1601, name: `Brood of Nozdormu` },
  { value: 1602, name: `Silvermoon City` },
  { value: 1603, name: `Silvermoon City` },
  { value: 1604, name: `Silvermoon City` },
  { value: 1605, name: `Dragonflight,Bronze` },
  { value: 1606, name: `Creature` },
  { value: 1607, name: `Creature` },
  { value: 1608, name: `Cenarion Circle` },
  { value: 1610, name: `PLAYER,BloodElf` },
  { value: 1611, name: `Ironforge` },
  { value: 1612, name: `Orgrimmar` },
  { value: 1613, name: `Might of Kalimdor` },
  { value: 1614, name: `Monster` },
  { value: 1615, name: `Steamwheedle Cartel` },
  { value: 1616, name: `RC Objects` },
  { value: 1617, name: `RC Enemies` },
  { value: 1618, name: `Ironforge` },
  { value: 1619, name: `Orgrimmar` },
  { value: 1620, name: `Enemy` },
  { value: 1621, name: `Blue` },
  { value: 1622, name: `Red` },
  { value: 1623, name: `Tranquillien` },
  { value: 1624, name: `Argent Dawn` },
  { value: 1625, name: `Argent Dawn` },
  { value: 1626, name: `Undead,Scourge` },
  { value: 1627, name: `Farstriders` },
  { value: 1628, name: `Tranquillien` },
  { value: 1629, name: `PLAYER,Draenei` },
  { value: 1630, name: `Scourge Invaders` },
  { value: 1634, name: `Scourge Invaders` },
  { value: 1635, name: `Steamwheedle Cartel` },
  { value: 1636, name: `Farstriders` },
  { value: 1637, name: `Farstriders` },
  { value: 1638, name: `Exodar` },
  { value: 1639, name: `Exodar` },
  { value: 1640, name: `Exodar` },
  { value: 1641, name: `Warsong Outriders` },
  { value: 1642, name: `Silverwing Sentinels` },
  { value: 1643, name: `Troll,Forest` },
  { value: 1644, name: `The Sons of Lothar` },
  { value: 1645, name: `The Sons of Lothar` },
  { value: 1646, name: `Exodar` },
  { value: 1647, name: `Exodar` },
  { value: 1648, name: `The Sons of Lothar` },
  { value: 1649, name: `The Sons of Lothar` },
  { value: 1650, name: `TheMag'har` },
  { value: 1651, name: `TheMag'har` },
  { value: 1652, name: `TheMag'har` },
  { value: 1653, name: `TheMag'har` },
  { value: 1654, name: `Exodar` },
  { value: 1655, name: `Exodar` },
  { value: 1656, name: `Silvermoon City` },
  { value: 1657, name: `Silvermoon City` },
  { value: 1658, name: `Silvermoon City` },
  { value: 1659, name: `Cenarion Expedition` },
  { value: 1660, name: `Cenarion Expedition` },
  { value: 1661, name: `Cenarion Expedition` },
  { value: 1662, name: `Fel Orc` },
  { value: 1663, name: `Fel Orc Ghost` },
  { value: 1664, name: `Sons of Lothar Ghosts` },
  { value: 1665, name: `None` },
  { value: 1666, name: `Honor Hold` },
  { value: 1667, name: `Honor Hold` },
  { value: 1668, name: `Thrallmar` },
  { value: 1669, name: `Thrallmar` },
  { value: 1670, name: `Thrallmar` },
  { value: 1671, name: `Honor Hold` },
  { value: 1672, name: `Test Faction 1` },
  { value: 1673, name: `To WoW-Flag` },
  { value: 1674, name: `Test Faction 4` },
  { value: 1675, name: `Test Faction 3` },
  { value: 1676, name: `ToWoW-Flag Trigger Horde(DND)` },
  { value: 1677, name: `ToWoW-Flag Trigger Alliance(DND)` },
  { value: 1678, name: `Ethereum` },
  { value: 1679, name: `Broken` },
  { value: 1680, name: `Elemental` },
  { value: 1681, name: `Earth Elemental` },
  { value: 1682, name: `Fighting Robots` },
  { value: 1683, name: `Actor Good` },
  { value: 1684, name: `Actor Evil` },
  { value: 1685, name: `Stillpine Furbolg` },
  { value: 1686, name: `Stillpine Furbolg` },
  { value: 1687, name: `Crazed Owlkin` },
  { value: 1688, name: `Chess Alliance` },
  { value: 1689, name: `Chess Horde` },
  { value: 1690, name: `Chess Alliance` },
  { value: 1691, name: `Chess Horde` },
  { value: 1692, name: `Monster Spar` },
  { value: 1693, name: `Monster Spar Buddy` },
  { value: 1694, name: `Exodar` },
  { value: 1695, name: `Silvermoon City` },
  { value: 1696, name: `The Violet Eye` },
  { value: 1697, name: `Fel Orc` },
  { value: 1698, name: `Exodar` },
  { value: 1699, name: `Exodar` },
  { value: 1700, name: `Exodar` },
  { value: 1701, name: `Sunhawks` },
  { value: 1702, name: `Sunhawks` },
  { value: 1703, name: `Training Dummy` },
  { value: 1704, name: `Fel Orc` },
  { value: 1705, name: `Fel Orc` },
  { value: 1706, name: `Fungal Giant` },
  { value: 1707, name: `Sporeggar` },
  { value: 1708, name: `Sporeggar` },
  { value: 1709, name: `Sporeggar` },
  { value: 1710, name: `Cenarion Expedition` },
  { value: 1711, name: `Monster,Predator` },
  { value: 1712, name: `Monster,Prey` },
  { value: 1713, name: `Monster,Prey` },
  { value: 1714, name: `Sunhawks` },
  { value: 1715, name: `VoidAnomaly` },
  { value: 1716, name: `Hyjal Defenders` },
  { value: 1717, name: `Hyjal Defenders` },
  { value: 1718, name: `Hyjal Defenders` },
  { value: 1719, name: `Hyjal Defenders` },
  { value: 1720, name: `Hyjal Invaders` },
  { value: 1721, name: `Kurenai` },
  { value: 1722, name: `Kurenai` },
  { value: 1723, name: `Kurenai` },
  { value: 1724, name: `Kurenai` },
  { value: 1725, name: `Earthen Ring` },
  { value: 1726, name: `Earthen Ring` },
  { value: 1727, name: `Earthen Ring` },
  { value: 1728, name: `Cenarion Expedition` },
  { value: 1729, name: `Thrallmar` },
  { value: 1730, name: `The Consortium` },
  { value: 1731, name: `The Consortium` },
  { value: 1732, name: `Alliance Generic` },
  { value: 1733, name: `Alliance Generic` },
  { value: 1734, name: `Horde Generic` },
  { value: 1735, name: `Horde Generic` },
  { value: 1736, name: `Monster Spar Buddy` },
  { value: 1737, name: `Honor Hold` },
  { value: 1738, name: `Arakkoa` },
  { value: 1739, name: `Zangarmarsh Banner(Alliance)` },
  { value: 1740, name: `Zangarmarsh Banner(Horde)` },
  { value: 1741, name: `The Sha'tar` },
  { value: 1742, name: `Zangarmarsh Banner(Neutral)` },
  { value: 1743, name: `The Aldor` },
  { value: 1744, name: `The Scryers` },
  { value: 1745, name: `Silvermoon City` },
  { value: 1746, name: `The Scryers` },
  { value: 1747, name: `Caverns of Time-Thrall` },
  { value: 1748, name: `Caverns of Time-Durnholde` },
  { value: 1749, name: `Caverns of Time-Southshore Guards` },
  { value: 1750, name: `Shadow Council Covert` },
  { value: 1751, name: `Monster` },
  { value: 1752, name: `Dark Portal Attacker,Legion` },
  { value: 1753, name: `Dark Portal Attacker,Legion` },
  { value: 1754, name: `Dark Portal Attacker,Legion` },
  { value: 1755, name: `Dark Portal Defender,Alliance` },
  { value: 1756, name: `Dark Portal Defender,Alliance` },
  { value: 1757, name: `Dark Portal Defender,Alliance` },
  { value: 1758, name: `Dark Portal Defender,Horde` },
  { value: 1759, name: `Dark Portal Defender,Horde` },
  { value: 1760, name: `Dark Portal Defender,Horde` },
  { value: 1761, name: `Inciter Trigger` },
  { value: 1762, name: `Inciter Trigger 2` },
  { value: 1763, name: `Inciter Trigger 3` },
  { value: 1764, name: `Inciter Trigger 4` },
  { value: 1765, name: `Inciter Trigger 5` },
  { value: 1766, name: `Argent Dawn` },
  { value: 1767, name: `Argent Dawn` },
  { value: 1768, name: `Demon` },
  { value: 1769, name: `Demon` },
  { value: 1770, name: `Actor Good` },
  { value: 1771, name: `Actor Evil` },
  { value: 1772, name: `Mana Creature` },
  { value: 1773, name: `Khadgar's Servant` },
  { value: 1774, name: `Friendly` },
  { value: 1775, name: `The Sha'tar` },
  { value: 1776, name: `The Aldor` },
  { value: 1777, name: `The Aldor` },
  { value: 1778, name: `The Scale of the Sands` },
  { value: 1779, name: `Keepers of Time` },
  { value: 1780, name: `Bladespire Clan` },
  { value: 1781, name: `Bloodmaul Clan` },
  { value: 1782, name: `Bladespire Clan` },
  { value: 1783, name: `Bloodmaul Clan` },
  { value: 1784, name: `Bladespire Clan` },
  { value: 1785, name: `Bloodmaul Clan` },
  { value: 1786, name: `Demon` },
  { value: 1787, name: `Monster` },
  { value: 1788, name: `The Consortium` },
  { value: 1789, name: `Sunhawks` },
  { value: 1790, name: `Bladespire Clan` },
  { value: 1791, name: `Bloodmaul Clan` },
  { value: 1792, name: `FelOrc` },
  { value: 1793, name: `Sunhawks` },
  { value: 1794, name: `Protectorate` },
  { value: 1795, name: `Protectorate` },
  { value: 1796, name: `Ethereum` },
  { value: 1797, name: `Protectorate` },
  { value: 1798, name: `Arcane Annihilator(DNR)` },
  { value: 1799, name: `Ethereum Sparbuddy` },
  { value: 1800, name: `Ethereum` },
  { value: 1801, name: `Horde` },
  { value: 1802, name: `Alliance` },
  { value: 1803, name: `Ambient` },
  { value: 1804, name: `Ambient` },
  { value: 1805, name: `The Aldor` },
  { value: 1806, name: `Friendly` },
  { value: 1807, name: `Protectorate` },
  { value: 1808, name: `Kirin'Var-Belmara` },
  { value: 1809, name: `Kirin'Var-Cohlien` },
  { value: 1810, name: `Kirin'Var-Dathric` },
  { value: 1811, name: `Kirin'Var-Luminrath` },
  { value: 1812, name: `Friendly` },
  { value: 1813, name: `Servant of Illidan` },
  { value: 1814, name: `Monster Spar Buddy` },
  { value: 1815, name: `Beast-Wolf` },
  { value: 1816, name: `Friendly` },
  { value: 1818, name: `Lower City` },
  { value: 1819, name: `Alliance Generic` },
  { value: 1820, name: `Ashtongue Deathsworn` },
  { value: 1821, name: `Spirits of Shadowmoon 1` },
  { value: 1822, name: `Spirits of Shadowmoon 2` },
  { value: 1823, name: `Ethereum` },
  { value: 1824, name: `Netherwing` },
  { value: 1825, name: `Demon` },
  { value: 1826, name: `Servant of Illidan` },
  { value: 1827, name: `Wyrmcult` },
  { value: 1828, name: `Treant` },
  { value: 1829, name: `Leotheras Demon I` },
  { value: 1830, name: `Leotheras Demon II` },
  { value: 1831, name: `Leotheras Demon III` },
  { value: 1832, name: `Leotheras Demon IV` },
  { value: 1833, name: `Leotheras Demon V` },
  { value: 1834, name: `Azaloth` },
  { value: 1835, name: `Horde Generic` },
  { value: 1836, name: `The Consortium` },
  { value: 1837, name: `Sporeggar` },
  { value: 1838, name: `The Scryers` },
  { value: 1839, name: `Rock Flayer` },
  { value: 1840, name: `Flayer Hunter` },
  { value: 1841, name: `Shadowmoon Shade` },
  { value: 1842, name: `Legion Communicator` },
  { value: 1843, name: `Servant of Illidan` },
  { value: 1844, name: `The Aldor` },
  { value: 1845, name: `The Scryers` },
  { value: 1846, name: `Ravenswood Ancients` },
  { value: 1847, name: `Monster Spar` },
  { value: 1848, name: `Monster Spar Buddy` },
  { value: 1849, name: `Servant of Illidan` },
  { value: 1850, name: `Netherwing` },
  { value: 1851, name: `Lower City` },
  { value: 1852, name: `Chess,Friendly to All Chess` },
  { value: 1853, name: `Servant of Illidan` },
  { value: 1854, name: `The Aldor` },
  { value: 1855, name: `The Scryers` },
  { value: 1856, name: `Sha'tari Skyguard` },
  { value: 1857, name: `Friendly` },
  { value: 1858, name: `Ashtongue Deathsworn` },
  { value: 1859, name: `Maiev` },
  { value: 1860, name: `Skettis Shadowy Arakkoa` },
  { value: 1862, name: `Skettis Arakkoa` },
  { value: 1863, name: `Orc,Dragonmaw` },
  { value: 1864, name: `Dragonmaw Enemy` },
  { value: 1865, name: `Orc,Dragonmaw` },
  { value: 1866, name: `Ashtongue Deathsworn` },
  { value: 1867, name: `Maiev` },
  { value: 1868, name: `Monster Spar Buddy` },
  { value: 1869, name: `Arakkoa` },
  { value: 1870, name: `Sha'tari Skyguard` },
  { value: 1871, name: `Skettis Arakkoa` },
  { value: 1872, name: `Ogri'la` },
  { value: 1873, name: `Rock Flayer` },
  { value: 1874, name: `Ogri'la` },
  { value: 1875, name: `The Aldor` },
  { value: 1876, name: `The Scryers` },
  { value: 1877, name: `Orc,Dragonmaw` },
  { value: 1878, name: `Frenzy` },
  { value: 1879, name: `Skyguard Enemy` },
  { value: 1880, name: `Orc,Dragonmaw` },
  { value: 1881, name: `Skettis Arakkoa` },
  { value: 1882, name: `Servant of Illidan` },
  { value: 1883, name: `Theramore Deserter` },
  { value: 1884, name: `Tuskarr` },
  { value: 1885, name: `Vrykul` },
  { value: 1886, name: `Creature` },
  { value: 1887, name: `Creature` },
  { value: 1888, name: `Northsea Pirates` },
  { value: 1889, name: `UNUSED` },
  { value: 1890, name: `Troll,Amani` },
  { value: 1891, name: `Valiance Expedition` },
  { value: 1892, name: `Valiance Expedition` },
  { value: 1893, name: `Valiance Expedition` },
  { value: 1894, name: `Vrykul` },
  { value: 1895, name: `Vrykul` },
  { value: 1896, name: `Darkmoon Faire` },
  { value: 1897, name: `The Hand of Vengeance` },
  { value: 1898, name: `Valiance Expedition` },
  { value: 1899, name: `Valiance Expedition` },
  { value: 1900, name: `The Hand of Vengeance` },
  { value: 1901, name: `Horde Expedition` },
  { value: 1902, name: `Actor Evil` },
  { value: 1904, name: `Actor Evil` },
  { value: 1905, name: `Tamed Plaguehound` },
  { value: 1906, name: `Spotted Gryphon` },
  { value: 1907, name: `Test Faction 1` },
  { value: 1908, name: `Test Faction 1` },
  { value: 1909, name: `Beast-Raptor` },
  { value: 1910, name: `Vrykul(AncientSpirit1)` },
  { value: 1911, name: `Vrykul(AncientSiprit2)` },
  { value: 1912, name: `Vrykul(AncientSiprit3)` },
  { value: 1913, name: `CTF-Flag-Alliance` },
  { value: 1914, name: `Vrykul` },
  { value: 1915, name: `Test` },
  { value: 1916, name: `Maiev` },
  { value: 1917, name: `Creature` },
  { value: 1918, name: `Horde Expedition` },
  { value: 1919, name: `Vrykul Gladiator` },
  { value: 1920, name: `Valgarde Combatant` },
  { value: 1921, name: `The Taunka` },
  { value: 1922, name: `The Taunka` },
  { value: 1923, name: `The Taunka` },
  { value: 1924, name: `Monster,Zone Force Reaction 1` },
  { value: 1925, name: `Monster` },
  { value: 1926, name: `Explorer's League` },
  { value: 1927, name: `Explorer's League` },
  { value: 1928, name: `The Hand of Vengeance` },
  { value: 1929, name: `The Hand of Vengeance` },
  { value: 1930, name: `Ram Racing Powerup DND` },
  { value: 1931, name: `Ram Racing Trap DND` },
  { value: 1932, name: `Elemental` },
  { value: 1933, name: `Friendly` },
  { value: 1934, name: `Actor Good` },
  { value: 1935, name: `Actor Good` },
  { value: 1936, name: `Craig's Squirrels` },
  { value: 1937, name: `Craig's Squirrels` },
  { value: 1938, name: `Craig's Squirrels` },
  { value: 1939, name: `Craig's Squirrels` },
  { value: 1940, name: `Craig's Squirrels` },
  { value: 1941, name: `Craig's Squirrels` },
  { value: 1942, name: `Craig's Squirrels` },
  { value: 1943, name: `Craig's Squirrels` },
  { value: 1944, name: `Craig's Squirrels` },
  { value: 1945, name: `Craig's Squirrels` },
  { value: 1947, name: `Craig's Squirrels` },
  { value: 1948, name: `Blue` },
  { value: 1949, name: `The Kalu' ak` },
  { value: 1950, name: `The Kalu' ak` },
  { value: 1951, name: `Darnassus` },
  { value: 1952, name: `Holiday-WaterBarrel` },
  { value: 1953, name: `Monster,Predator` },
  { value: 1954, name: `Iron Dwarves` },
  { value: 1955, name: `Iron Dwarves` },
  { value: 1956, name: `Shattered Sun Offensive` },
  { value: 1957, name: `Shattered Sun Offensive` },
  { value: 1958, name: `Actor Evil` },
  { value: 1959, name: `Actor Evil` },
  { value: 1960, name: `Shattered Sun Offensive` },
  { value: 1961, name: `Fighting Vanity Pet` },
  { value: 1962, name: `Undead,Scourge` },
  { value: 1963, name: `Demon` },
  { value: 1964, name: `Undead,Scourge` },
  { value: 1965, name: `Monster Spar` },
  { value: 1966, name: `Murloc` },
  { value: 1967, name: `Shattered Sun Offensive` },
  { value: 1968, name: `Murloc,Winterfin` },
  { value: 1969, name: `Murloc` },
  { value: 1970, name: `Monster` },
  { value: 1971, name: `Friendly,Force Reaction` },
  { value: 1972, name: `Object,Force Reaction` },
  { value: 1973, name: `Valiance Expedition` },
  { value: 1974, name: `Valiance Expedition` },
  { value: 1975, name: `Undead,Scourge` },
  { value: 1976, name: `Valiance Expedition` },
  { value: 1977, name: `Valiance Expedition` },
  { value: 1978, name: `Warsong Offensive` },
  { value: 1979, name: `Warsong Offensive` },
  { value: 1980, name: `Warsong Offensive` },
  { value: 1981, name: `Warsong Offensive` },
  { value: 1982, name: `Undead,Scourge` },
  { value: 1983, name: `Monster Spar` },
  { value: 1984, name: `Monster Spar Buddy` },
  { value: 1985, name: `Monster` },
  { value: 1986, name: `Escortee` },
  { value: 1987, name: `Cenarion Expedition` },
  { value: 1988, name: `Undead,Scourge` },
  { value: 1989, name: `Poacher` },
  { value: 1990, name: `Ambient` },
  { value: 1991, name: `Undead,Scourge` },
  { value: 1992, name: `Monster` },
  { value: 1993, name: `Monster Spar` },
  { value: 1994, name: `Monster Spar Buddy` },
  { value: 1995, name: `CTF-Flag-Alliance` },
  { value: 1997, name: `CTF-Flag-Alliance` },
  { value: 1998, name: `Holiday Monster` },
  { value: 1999, name: `Monster,Prey` },
  { value: 2000, name: `Monster,Prey` },
  { value: 2001, name: `Furbolg,Redfang` },
  { value: 2003, name: `Furbolg,Frostpaw` },
  { value: 2004, name: `Valiance Expedition` },
  { value: 2005, name: `Undead,Scourge` },
  { value: 2006, name: `Kirin Tor` },
  { value: 2007, name: `Kirin Tor` },
  { value: 2008, name: `Kirin Tor` },
  { value: 2009, name: `Kirin Tor` },
  { value: 2010, name: `The Wyrmrest Accord` },
  { value: 2011, name: `The Wyrmrest Accord` },
  { value: 2012, name: `The Wyrmrest Accord` },
  { value: 2013, name: `The Wyrmrest Accord` },
  { value: 2014, name: `Azjol-Nerub` },
  { value: 2016, name: `Azjol-Nerub` },
  { value: 2017, name: `Azjol-Nerub` },
  { value: 2018, name: `Undead,Scourge` },
  { value: 2019, name: `The Taunka` },
  { value: 2020, name: `Warsong Offensive` },
  { value: 2021, name: `REUSE` },
  { value: 2022, name: `Monster` },
  { value: 2023, name: `Scourge Invaders` },
  { value: 2024, name: `The Hand of Vengeance` },
  { value: 2025, name: `The Silver Covenant` },
  { value: 2026, name: `The Silver Covenant` },
  { value: 2027, name: `The Silver Covenant` },
  { value: 2028, name: `Ambient` },
  { value: 2029, name: `Monster, Predator` },
  { value: 2030, name: `Monster, Predator` },
  { value: 2031, name: `Horde Generic` },
  { value: 2032, name: `GrizzlyHills Trapper` },
  { value: 2033, name: `Monster` },
  { value: 2034, name: `Warsong Offensive` },
  { value: 2035, name: `Undead, Scourge` },
  { value: 2036, name: `Friendly` },
  { value: 2037, name: `Valiance Expedition` },
  { value: 2038, name: `Ambient` },
  { value: 2039, name: `Monster` },
  { value: 2040, name: `Valiance Expedition` },
  { value: 2041, name: `The Wyrmrest Accord` },
  { value: 2042, name: `Undead, Scourge` },
  { value: 2043, name: `Undead, Scourge` },
  { value: 2044, name: `Valiance Expedition` },
  { value: 2045, name: `Warsong Offensive` },
  { value: 2046, name: `Escortee` },
  { value: 2047, name: `The Kalu' ak` },
  { value: 2048, name: `Scourge Invaders` },
  { value: 2049, name: `Scourge Invaders` },
  { value: 2050, name: `Knights of the EbonBlade` },
  { value: 2051, name: `Knights of the EbonBlade` },
  { value: 2052, name: `Wrathgate Scourge` },
  { value: 2053, name: `Wrathgate Alliance` },
  { value: 2054, name: `Wrathgate Horde` },
  { value: 2055, name: `Monster Spar` },
  { value: 2056, name: `Monster Spar Buddy` },
  { value: 2057, name: `Monster, ZoneForceReaction 2` },
  { value: 2058, name: `CTF-Flag-Horde` },
  { value: 2059, name: `CTF-Flag-Neutral` },
  { value: 2060, name: `Frenzyheart Tribe` },
  { value: 2061, name: `Frenzyheart Tribe` },
  { value: 2062, name: `Frenzyheart Tribe` },
  { value: 2063, name: `The Oracles` },
  { value: 2064, name: `The Oracles` },
  { value: 2065, name: `The Oracles` },
  { value: 2066, name: `The Oracles` },
  { value: 2067, name: `The Wyrmrest Accord` },
  { value: 2068, name: `Undead, Scourge` },
  { value: 2069, name: `Troll, Drakkari` },
  { value: 2070, name: `Argent Crusade` },
  { value: 2071, name: `Argent Crusade` },
  { value: 2072, name: `Argent Crusade` },
  { value: 2073, name: `Argent Crusade` },
  { value: 2074, name: `Caverns of Time-Durnholde` },
  { value: 2075, name: `CoT Scourge` },
  { value: 2076, name: `CoT Arthas` },
  { value: 2077, name: `CoT Arthas` },
  { value: 2078, name: `CoT Stratholme Citizen` },
  { value: 2079, name: `CoT Arthas` },
  { value: 2080, name: `Undead, Scourge` },
  { value: 2081, name: `Freya` },
  { value: 2082, name: `Undead, Scourge` },
  { value: 2083, name: `Undead, Scourge` },
  { value: 2084, name: `Undead, Scourge` },
  { value: 2085, name: `Undead, Scourge` },
  { value: 2086, name: `Argent Dawn` },
  { value: 2087, name: `Argent Dawn` },
  { value: 2088, name: `Actor Evil` },
  { value: 2089, name: `Scarlet Crusade` },
  { value: 2090, name: `Mount-Taxi-Alliance` },
  { value: 2091, name: `Mount-Taxi-Horde` },
  { value: 2092, name: `Mount-Taxi-Neutral` },
  { value: 2093, name: `Undead, Scourge` },
  { value: 2094, name: `Undead, Scourge` },
  { value: 2095, name: `Scarlet Crusade` },
  { value: 2096, name: `Scarlet Crusade` },
  { value: 2097, name: `Undead, Scourge` },
  { value: 2098, name: `Elemental, Air` },
  { value: 2099, name: `Elemental, Water` },
  { value: 2100, name: `Undead, Scourge` },
  { value: 2101, name: `Actor Evil` },
  { value: 2102, name: `Actor Evil` },
  { value: 2103, name: `Scarlet Crusade` },
  { value: 2104, name: `Monster Spar` },
  { value: 2105, name: `Monster Spar Buddy` },
  { value: 2106, name: `Ambient` },
  { value: 2107, name: `The Sons of Hodir` },
  { value: 2108, name: `Iron Giants` },
  { value: 2109, name: `Frost Vrykul` },
  { value: 2110, name: `Friendly` },
  { value: 2111, name: `Monster` },
  { value: 2112, name: `The Sons of Hodir` },
  { value: 2113, name: `Frost Vrykul` },
  { value: 2114, name: `Vrykul` },
  { value: 2115, name: `Actor Good` },
  { value: 2116, name: `Vrykul` },
  { value: 2117, name: `Actor Good` },
  { value: 2118, name: `Earthen` },
  { value: 2119, name: `Monster Referee` },
  { value: 2120, name: `Monster Referee` },
  { value: 2121, name: `The Sunreavers` },
  { value: 2122, name: `The Sunreavers` },
  { value: 2123, name: `The Sunreavers` },
  { value: 2124, name: `Monster` },
  { value: 2125, name: `Frost Vrykul` },
  { value: 2126, name: `Frost Vrykul` },
  { value: 2127, name: `Ambient` },
  { value: 2128, name: `Hyldsmeet` },
  { value: 2129, name: `The Sunreavers` },
  { value: 2130, name: `The Silver Covenant` },
  { value: 2131, name: `Argent Crusade` },
  { value: 2132, name: `Warsong Offensive` },
  { value: 2133, name: `Frost Vrykul` },
  { value: 2134, name: `Argent Crusade` },
  { value: 2135, name: `Friendly` },
  { value: 2136, name: `Ambient` },
  { value: 2137, name: `Friendly` },
  { value: 2138, name: `Argent Crusade` },
  { value: 2139, name: `ScourgeInvaders` },
  { value: 2140, name: `Friendly` },
  { value: 2141, name: `Friendly` },
  { value: 2142, name: `Alliance` },
  { value: 2143, name: `Valiance Expedition` },
  { value: 2144, name: `Knights of the EbonBlade` },
  { value: 2145, name: `Scourge Invaders` },
  { value: 2148, name: `The Kalu'ak` },
  { value: 2150, name: `Monster Spar Buddy` },
  { value: 2155, name: `Ironforge` },
  { value: 2156, name: `Monster, Predator` },
  { value: 2176, name: `ActorGood` },
  { value: 2178, name: `ActorGood` },
  { value: 2189, name: `Hates Everything` },
  { value: 2190, name: `Hates Everything` },
  { value: 2191, name: `Hates Everything` },
  { value: 2209, name: `Undead, Scourge` },
  { value: 2210, name: `Silvermoon City` },
  { value: 2212, name: `Undead,Scourge` },
  { value: 2214, name: `Knights of the EbonBlade` },
  { value: 2216, name: `The Ashen Verdict` },
  { value: 2217, name: `The Ashen Verdict` },
  { value: 2218, name: `The Ashen Verdict` },
  { value: 2219, name: `The Ashen Verdict` },
  { value: 2226, name: `Knights of the EbonBlade` },
  { value: 2230, name: `ArgentCrusade` },
  { value: 2235, name: `CTF-Flag-Horde 2` },
  { value: 2236, name: `CTF-Flag-Alliance 2` },
];
