import { Option } from '../../types/general';

export const SPELL_DBC_EFFECT: Option[] = [
  { value: 0, name: 'NONE' },
  { value: 1, name: 'INSTAKILL' },
  { value: 2, name: 'SCHOOL_DAMAGE' },
  { value: 3, name: 'DUMMY' },
  { value: 4, name: 'PORTAL_TELEPORT unused' },
  { value: 5, name: 'TELEPORT_UNITS' },
  { value: 6, name: 'APPLY_AURA' },
  { value: 7, name: 'ENVIRONMENTAL_DAMAGE' },
  { value: 8, name: 'POWER_DRAIN' },
  { value: 9, name: 'HEALTH_LEECH' },
  { value: 10, name: 'HEAL' },
  { value: 11, name: 'BIND' },
  { value: 12, name: 'PORTAL' },
  { value: 13, name: 'RITUAL_BASE unused' },
  { value: 14, name: 'RITUAL_SPECIALIZE unused' },
  { value: 15, name: 'RITUAL_ACTIVATE_PORTAL unused' },
  { value: 16, name: 'QUEST_COMPLETE' },
  { value: 17, name: 'WEAPON_DAMAGE_NOSCHOOL' },
  { value: 18, name: 'RESURRECT' },
  { value: 19, name: 'ADD_EXTRA_ATTACKS' },
  { value: 20, name: 'DODGE one spell: Dodge' },
  { value: 21, name: 'EVADE one spell: Evade (DND)' },
  { value: 22, name: 'PARRY' },
  { value: 23, name: 'BLOCK one spell: Block' },
  { value: 24, name: 'CREATE_ITEM' },
  { value: 25, name: 'WEAPON' },
  { value: 26, name: 'DEFENSE one spell: Defense' },
  { value: 27, name: 'PERSISTENT_AREA_AURA' },
  { value: 28, name: 'SUMMON' },
  { value: 29, name: 'LEAP' },
  { value: 30, name: 'ENERGIZE' },
  { value: 31, name: 'WEAPON_PERCENT_DAMAGE' },
  { value: 32, name: 'TRIGGER_MISSILE' },
  { value: 33, name: 'OPEN_LOCK' },
  { value: 34, name: 'SUMMON_CHANGE_ITEM' },
  { value: 35, name: 'APPLY_AREA_AURA_PARTY' },
  { value: 36, name: 'LEARN_SPELL' },
  { value: 37, name: 'SPELL_DEFENSE one spell: SPELLDEFENSE (DND)' },
  { value: 38, name: 'DISPEL' },
  { value: 39, name: 'LANGUAGE' },
  { value: 40, name: 'DUAL_WIELD' },
  { value: 41, name: 'JUMP' },
  { value: 42, name: 'JUMP_DEST' },
  { value: 43, name: 'TELEPORT_UNITS_FACE_CASTER' },
  { value: 44, name: 'SKILL_STEP' },
  { value: 45, name: 'ADD_HONOR honor/pvp related' },
  { value: 46, name: 'SPAWN clientside, unit appears as if it was just spawned' },
  { value: 47, name: 'TRADE_SKILL' },
  { value: 48, name: 'STEALTH one spell: Base Stealth' },
  { value: 49, name: 'DETECT one spell: Detect' },
  { value: 50, name: 'TRANS_DOOR' },
  { value: 51, name: 'FORCE_CRITICAL_HIT unused' },
  { value: 52, name: 'GUARANTEE_HIT one spell: zzOLDCritical Shot' },
  { value: 53, name: 'ENCHANT_ITEM' },
  { value: 54, name: 'ENCHANT_ITEM_TEMPORARY' },
  { value: 55, name: 'TAMECREATURE' },
  { value: 56, name: 'SUMMON_PET' },
  { value: 57, name: 'LEARN_PET_SPELL' },
  { value: 58, name: 'WEAPON_DAMAGE' },
  { value: 59, name: 'CREATE_RANDOM_ITEM create item base at spell specific loot' },
  { value: 60, name: 'PROFICIENCY' },
  { value: 61, name: 'SEND_EVENT' },
  { value: 62, name: 'POWER_BURN' },
  { value: 63, name: 'THREAT' },
  { value: 64, name: 'TRIGGER_SPELL' },
  { value: 65, name: 'APPLY_AREA_AURA_RAID' },
  { value: 66, name: 'CREATE_MANA_GEM (possibly recharge it, misc - is item ID)' },
  { value: 67, name: 'HEAL_MAX_HEALTH' },
  { value: 68, name: 'INTERRUPT_CAST' },
  { value: 69, name: 'DISTRACT' },
  { value: 70, name: 'PULL one spell: Distract Move' },
  { value: 71, name: 'PICKPOCKET' },
  { value: 72, name: 'ADD_FARSIGHT' },
  { value: 73, name: 'UNTRAIN_TALENTS' },
  { value: 74, name: 'APPLY_GLYPH' },
  { value: 75, name: 'HEAL_MECHANICAL one spell: Mechanical Patch Kit' },
  { value: 76, name: 'SUMMON_OBJECT_WILD' },
  { value: 77, name: 'SCRIPT_EFFECT' },
  { value: 78, name: 'ATTACK' },
  { value: 79, name: 'SANCTUARY' },
  { value: 80, name: 'ADD_COMBO_POINTS' },
  { value: 81, name: 'CREATE_HOUSE one spell: Create House (TEST)' },
  { value: 82, name: 'BIND_SIGHT' },
  { value: 83, name: 'DUEL' },
  { value: 84, name: 'STUCK' },
  { value: 85, name: 'SUMMON_PLAYER' },
  { value: 86, name: 'ACTIVATE_OBJECT' },
  { value: 87, name: 'GAMEOBJECT_DAMAGE' },
  { value: 88, name: 'GAMEOBJECT_REPAIR' },
  { value: 89, name: 'GAMEOBJECT_SET_DESTRUCTION_STATE' },
  { value: 90, name: 'KILL_CREDIT Kill credit but only for single person' },
  { value: 91, name: 'THREAT_ALL one spell: zzOLDBrainwash' },
  { value: 92, name: 'ENCHANT_HELD_ITEM' },
  { value: 93, name: 'FORCE_DESELECT' },
  { value: 94, name: 'SELF_RESURRECT' },
  { value: 95, name: 'SKINNING' },
  { value: 96, name: 'CHARGE' },
  { value: 97, name: 'CAST_BUTTON (totem bar since 3.2.2a)' },
  { value: 98, name: 'KNOCK_BACK' },
  { value: 99, name: 'DISENCHANT' },
  { value: 100, name: 'INEBRIATE' },
  { value: 101, name: 'FEED_PET' },
  { value: 102, name: 'DISMISS_PET' },
  { value: 103, name: 'REPUTATION' },
  { value: 104, name: 'SUMMON_OBJECT_SLOT1' },
  { value: 105, name: 'SUMMON_OBJECT_SLOT2' },
  { value: 106, name: 'SUMMON_OBJECT_SLOT3' },
  { value: 107, name: 'SUMMON_OBJECT_SLOT4' },
  { value: 108, name: 'DISPEL_MECHANIC' },
  { value: 109, name: 'SUMMON_DEAD_PET' },
  { value: 110, name: 'DESTROY_ALL_TOTEMS' },
  { value: 111, name: 'DURABILITY_DAMAGE' },
  { value: 112, name: '112 unused' },
  { value: 113, name: 'RESURRECT_NEW' },
  { value: 114, name: 'ATTACK_ME' },
  { value: 115, name: 'DURABILITY_DAMAGE_PCT' },
  { value: 116, name: 'SKIN_PLAYER_CORPSE one spell: Remove Insignia, bg usage, required special corpse flags...' },
  { value: 117, name: 'SPIRIT_HEAL one spell: Spirit Heal' },
  { value: 118, name: 'SKILL professions and more' },
  { value: 119, name: 'APPLY_AREA_AURA_PET' },
  { value: 120, name: 'TELEPORT_GRAVEYARD one spell: Graveyard Teleport Test' },
  { value: 121, name: 'NORMALIZED_WEAPON_DMG' },
  { value: 122, name: '122 unused' },
  { value: 123, name: 'SEND_TAXI taxi/flight related (misc value is taxi path id)' },
  { value: 124, name: 'PULL_TOWARDS' },
  { value: 125, name: 'MODIFY_THREAT_PERCENT' },
  { value: 126, name: 'STEAL_BENEFICIAL_BUFF spell steal effect?' },
  { value: 127, name: 'PROSPECTING Prospecting spell' },
  { value: 128, name: 'APPLY_AREA_AURA_FRIEND' },
  { value: 129, name: 'APPLY_AREA_AURA_ENEMY' },
  { value: 130, name: 'REDIRECT_THREAT' },
  { value: 131, name: 'PLAYER_NOTIFICATION sound id in misc value (SoundEntries.dbc)' },
  { value: 132, name: 'PLAY_MUSIC sound id in misc value (SoundEntries.dbc)' },
  { value: 133, name: 'UNLEARN_SPECIALIZATION unlearn profession specialization' },
  { value: 134, name: 'KILL_CREDIT misc value is creature entry' },
  { value: 135, name: 'CALL_PET' },
  { value: 136, name: 'HEAL_PCT' },
  { value: 137, name: 'ENERGIZE_PCT' },
  { value: 138, name: 'LEAP_BACK Leap back' },
  { value: 139, name: 'CLEAR_QUEST Reset quest status (miscValue - quest ID)' },
  { value: 140, name: 'FORCE_CAST' },
  { value: 141, name: 'FORCE_CAST_WITH_VALUE' },
  { value: 142, name: 'TRIGGER_SPELL_WITH_VALUE' },
  { value: 143, name: 'APPLY_AREA_AURA_OWNER' },
  { value: 144, name: 'KNOCK_BACK_DEST' },
  { value: 145, name: 'PULL_TOWARDS_DEST Black Hole Effect' },
  { value: 146, name: 'ACTIVATE_RUNE' },
  { value: 147, name: 'QUEST_FAIL quest fail' },
  { value: 148, name: 'TRIGGER_MISSILE_SPELL_WITH_VALUE' },
  { value: 149, name: 'CHARGE_DEST' },
  { value: 150, name: 'QUEST_START' },
  { value: 151, name: 'TRIGGER_SPELL_2' },
  { value: 152, name: 'SUMMON_RAF_FRIEND summon Refer-a-Friend' },
  { value: 153, name: 'CREATE_TAMED_PET misc value is creature entry' },
  { value: 154, name: 'DISCOVER_TAXI' },
  {
    value: 155,
    name: 'TITAN_GRIP Allows you to equip two-handed axes, maces and swords in one hand, but you attack $49152s1% slower than normal.',
  },
  { value: 156, name: 'ENCHANT_ITEM_PRISMATIC' },
  { value: 157, name: 'CREATE_ITEM_2 create item or create item template and replace by some randon spell loot item' },
  { value: 158, name: 'MILLING milling' },
  { value: 159, name: 'ALLOW_RENAME_PET allow rename pet once again' },
  { value: 160, name: '1 spell example - 45534' },
  { value: 161, name: 'TALENT_SPEC_COUNT second talent spec (learn/revert)' },
  { value: 162, name: 'TALENT_SPEC_SELECT activate primary/secondary spec' },
  { value: 163, name: 'unused' },
  { value: 164, name: 'REMOVE_AURA' },
];

export const SPELL_DBC_APPLY_AURA_NAME: Option[] = [
  { value: 0, name: 'SPELL_AURA_NONE' },
  { value: 1, name: 'SPELL_AURA_BIND_SIGHT' },
  { value: 2, name: 'SPELL_AURA_MOD_POSSESS' },
  { value: 3, name: 'SPELL_AURA_PERIODIC_DAMAGE' },
  { value: 4, name: 'SPELL_AURA_DUMMY' },
  { value: 5, name: 'SPELL_AURA_MOD_CONFUSE' },
  { value: 6, name: 'SPELL_AURA_MOD_CHARM' },
  { value: 7, name: 'SPELL_AURA_MOD_FEAR' },
  { value: 8, name: 'SPELL_AURA_PERIODIC_HEAL' },
  { value: 9, name: 'SPELL_AURA_MOD_ATTACKSPEED' },
  { value: 10, name: 'SPELL_AURA_MOD_THREAT' },
  { value: 11, name: 'SPELL_AURA_MOD_TAUNT' },
  { value: 12, name: 'SPELL_AURA_MOD_STUN' },
  { value: 13, name: 'SPELL_AURA_MOD_DAMAGE_DONE' },
  { value: 14, name: 'SPELL_AURA_MOD_DAMAGE_TAKEN' },
  { value: 15, name: 'SPELL_AURA_DAMAGE_SHIELD' },
  { value: 16, name: 'SPELL_AURA_MOD_STEALTH' },
  { value: 17, name: 'SPELL_AURA_MOD_STEALTH_DETECT' },
  { value: 18, name: 'SPELL_AURA_MOD_INVISIBILITY' },
  { value: 19, name: 'SPELL_AURA_MOD_INVISIBILITY_DETECT' },
  { value: 20, name: 'SPELL_AURA_OBS_MOD_HEALTH' },
  { value: 21, name: 'SPELL_AURA_OBS_MOD_POWER' },
  { value: 22, name: 'SPELL_AURA_MOD_RESISTANCE' },
  { value: 23, name: 'SPELL_AURA_PERIODIC_TRIGGER_SPELL' },
  { value: 24, name: 'SPELL_AURA_PERIODIC_ENERGIZE' },
  { value: 25, name: 'SPELL_AURA_MOD_PACIFY' },
  { value: 26, name: 'SPELL_AURA_MOD_ROOT' },
  { value: 27, name: 'SPELL_AURA_MOD_SILENCE' },
  { value: 28, name: 'SPELL_AURA_REFLECT_SPELLS' },
  { value: 29, name: 'SPELL_AURA_MOD_STAT' },
  { value: 30, name: 'SPELL_AURA_MOD_SKILL' },
  { value: 31, name: 'SPELL_AURA_MOD_INCREASE_SPEED' },
  { value: 32, name: 'SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED' },
  { value: 33, name: 'SPELL_AURA_MOD_DECREASE_SPEED' },
  { value: 34, name: 'SPELL_AURA_MOD_INCREASE_HEALTH' },
  { value: 35, name: 'SPELL_AURA_MOD_INCREASE_ENERGY' },
  { value: 36, name: 'SPELL_AURA_MOD_SHAPESHIFT' },
  { value: 37, name: 'SPELL_AURA_EFFECT_IMMUNITY' },
  { value: 38, name: 'SPELL_AURA_STATE_IMMUNITY' },
  { value: 39, name: 'SPELL_AURA_SCHOOL_IMMUNITY' },
  { value: 40, name: 'SPELL_AURA_DAMAGE_IMMUNITY' },
  { value: 41, name: 'SPELL_AURA_DISPEL_IMMUNITY' },
  { value: 42, name: 'SPELL_AURA_PROC_TRIGGER_SPELL' },
  { value: 43, name: 'SPELL_AURA_PROC_TRIGGER_DAMAGE' },
  { value: 44, name: 'SPELL_AURA_TRACK_CREATURES' },
  { value: 45, name: 'SPELL_AURA_TRACK_RESOURCES' },
  { value: 46, name: 'SPELL_AURA_46' },
  { value: 47, name: 'SPELL_AURA_MOD_PARRY_PERCENT' },
  { value: 48, name: 'SPELL_AURA_48' },
  { value: 49, name: 'SPELL_AURA_MOD_DODGE_PERCENT' },
  { value: 50, name: 'SPELL_AURA_MOD_CRITICAL_HEALING_AMOUNT' },
  { value: 51, name: 'SPELL_AURA_MOD_BLOCK_PERCENT' },
  { value: 52, name: 'SPELL_AURA_MOD_WEAPON_CRIT_PERCENT' },
  { value: 53, name: 'SPELL_AURA_PERIODIC_LEECH' },
  { value: 54, name: 'SPELL_AURA_MOD_HIT_CHANCE' },
  { value: 55, name: 'SPELL_AURA_MOD_SPELL_HIT_CHANCE' },
  { value: 56, name: 'SPELL_AURA_TRANSFORM' },
  { value: 57, name: 'SPELL_AURA_MOD_SPELL_CRIT_CHANCE' },
  { value: 58, name: 'SPELL_AURA_MOD_INCREASE_SWIM_SPEED' },
  { value: 59, name: 'SPELL_AURA_MOD_DAMAGE_DONE_CREATURE' },
  { value: 60, name: 'SPELL_AURA_MOD_PACIFY_SILENCE' },
  { value: 61, name: 'SPELL_AURA_MOD_SCALE' },
  { value: 62, name: 'SPELL_AURA_PERIODIC_HEALTH_FUNNEL' },
  { value: 63, name: 'SPELL_AURA_63' },
  { value: 64, name: 'SPELL_AURA_PERIODIC_MANA_LEECH' },
  { value: 65, name: 'SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK' },
  { value: 66, name: 'SPELL_AURA_FEIGN_DEATH' },
  { value: 67, name: 'SPELL_AURA_MOD_DISARM' },
  { value: 68, name: 'SPELL_AURA_MOD_STALKED' },
  { value: 69, name: 'SPELL_AURA_SCHOOL_ABSORB' },
  { value: 70, name: 'SPELL_AURA_EXTRA_ATTACKS' },
  { value: 71, name: 'SPELL_AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL' },
  { value: 72, name: 'SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT' },
  { value: 73, name: 'SPELL_AURA_MOD_POWER_COST_SCHOOL' },
  { value: 74, name: 'SPELL_AURA_REFLECT_SPELLS_SCHOOL' },
  { value: 75, name: 'SPELL_AURA_MOD_LANGUAGE' },
  { value: 76, name: 'SPELL_AURA_FAR_SIGHT' },
  { value: 77, name: 'SPELL_AURA_MECHANIC_IMMUNITY' },
  { value: 78, name: 'SPELL_AURA_MOUNTED' },
  { value: 79, name: 'SPELL_AURA_MOD_DAMAGE_PERCENT_DONE' },
  { value: 80, name: 'SPELL_AURA_MOD_PERCENT_STAT' },
  { value: 81, name: 'SPELL_AURA_SPLIT_DAMAGE_PCT' },
  { value: 82, name: 'SPELL_AURA_WATER_BREATHING' },
  { value: 83, name: 'SPELL_AURA_MOD_BASE_RESISTANCE' },
  { value: 84, name: 'SPELL_AURA_MOD_REGEN' },
  { value: 85, name: 'SPELL_AURA_MOD_POWER_REGEN' },
  { value: 86, name: 'SPELL_AURA_CHANNEL_DEATH_ITEM' },
  { value: 87, name: 'SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN' },
  { value: 88, name: 'SPELL_AURA_MOD_HEALTH_REGEN_PERCENT' },
  { value: 89, name: 'SPELL_AURA_PERIODIC_DAMAGE_PERCENT' },
  { value: 90, name: 'SPELL_AURA_90' },
  { value: 91, name: 'SPELL_AURA_MOD_DETECT_RANGE' },
  { value: 92, name: 'SPELL_AURA_PREVENTS_FLEEING' },
  { value: 93, name: 'SPELL_AURA_MOD_UNATTACKABLE' },
  { value: 94, name: 'SPELL_AURA_INTERRUPT_REGEN' },
  { value: 95, name: 'SPELL_AURA_GHOST' },
  { value: 96, name: 'SPELL_AURA_SPELL_MAGNET' },
  { value: 97, name: 'SPELL_AURA_MANA_SHIELD' },
  { value: 98, name: 'SPELL_AURA_MOD_SKILL_TALENT' },
  { value: 99, name: 'SPELL_AURA_MOD_ATTACK_POWER' },
  { value: 100, name: 'SPELL_AURA_AURAS_VISIBLE' },
  { value: 101, name: 'SPELL_AURA_MOD_RESISTANCE_PCT' },
  { value: 102, name: 'SPELL_AURA_MOD_MELEE_ATTACK_POWER_VERSUS' },
  { value: 103, name: 'SPELL_AURA_MOD_TOTAL_THREAT' },
  { value: 104, name: 'SPELL_AURA_WATER_WALK' },
  { value: 105, name: 'SPELL_AURA_FEATHER_FALL' },
  { value: 106, name: 'SPELL_AURA_HOVER' },
  { value: 107, name: 'SPELL_AURA_ADD_FLAT_MODIFIER' },
  { value: 108, name: 'SPELL_AURA_ADD_PCT_MODIFIER' },
  { value: 109, name: 'SPELL_AURA_ADD_TARGET_TRIGGER' },
  { value: 110, name: 'SPELL_AURA_MOD_POWER_REGEN_PERCENT' },
  { value: 111, name: 'SPELL_AURA_ADD_CASTER_HIT_TRIGGER' },
  { value: 112, name: 'SPELL_AURA_OVERRIDE_CLASS_SCRIPTS' },
  { value: 113, name: 'SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN' },
  { value: 114, name: 'SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN_PCT' },
  { value: 115, name: 'SPELL_AURA_MOD_HEALING' },
  { value: 116, name: 'SPELL_AURA_MOD_REGEN_DURING_COMBAT' },
  { value: 117, name: 'SPELL_AURA_MOD_MECHANIC_RESISTANCE' },
  { value: 118, name: 'SPELL_AURA_MOD_HEALING_PCT' },
  { value: 119, name: 'SPELL_AURA_119' },
  { value: 120, name: 'SPELL_AURA_UNTRACKABLE' },
  { value: 121, name: 'SPELL_AURA_EMPATHY' },
  { value: 122, name: 'SPELL_AURA_MOD_OFFHAND_DAMAGE_PCT' },
  { value: 123, name: 'SPELL_AURA_MOD_TARGET_RESISTANCE' },
  { value: 124, name: 'SPELL_AURA_MOD_RANGED_ATTACK_POWER' },
  { value: 125, name: 'SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN' },
  { value: 126, name: 'SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN_PCT' },
  { value: 127, name: 'SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS' },
  { value: 128, name: 'SPELL_AURA_MOD_POSSESS_PET' },
  { value: 129, name: 'SPELL_AURA_MOD_SPEED_ALWAYS' },
  { value: 130, name: 'SPELL_AURA_MOD_MOUNTED_SPEED_ALWAYS' },
  { value: 131, name: 'SPELL_AURA_MOD_RANGED_ATTACK_POWER_VERSUS' },
  { value: 132, name: 'SPELL_AURA_MOD_INCREASE_ENERGY_PERCENT' },
  { value: 133, name: 'SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT' },
  { value: 134, name: 'SPELL_AURA_MOD_MANA_REGEN_INTERRUPT' },
  { value: 135, name: 'SPELL_AURA_MOD_HEALING_DONE' },
  { value: 136, name: 'SPELL_AURA_MOD_HEALING_DONE_PERCENT' },
  { value: 137, name: 'SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE' },
  { value: 138, name: 'SPELL_AURA_MOD_MELEE_HASTE' },
  { value: 139, name: 'SPELL_AURA_FORCE_REACTION' },
  { value: 140, name: 'SPELL_AURA_MOD_RANGED_HASTE' },
  { value: 141, name: 'SPELL_AURA_MOD_RANGED_AMMO_HASTE' },
  { value: 142, name: 'SPELL_AURA_MOD_BASE_RESISTANCE_PCT' },
  { value: 143, name: 'SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE' },
  { value: 144, name: 'SPELL_AURA_SAFE_FALL' },
  { value: 145, name: 'SPELL_AURA_MOD_PET_TALENT_POINTS' },
  { value: 146, name: 'SPELL_AURA_ALLOW_TAME_PET_TYPE' },
  { value: 147, name: 'SPELL_AURA_MECHANIC_IMMUNITY_MASK' },
  { value: 148, name: 'SPELL_AURA_RETAIN_COMBO_POINTS' },
  { value: 149, name: 'SPELL_AURA_REDUCE_PUSHBACK' },
  { value: 150, name: 'SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT' },
  { value: 151, name: 'SPELL_AURA_TRACK_STEALTHED' },
  { value: 152, name: 'SPELL_AURA_MOD_DETECTED_RANGE' },
  { value: 153, name: 'SPELL_AURA_SPLIT_DAMAGE_FLAT' },
  { value: 154, name: 'SPELL_AURA_MOD_STEALTH_LEVEL' },
  { value: 155, name: 'SPELL_AURA_MOD_WATER_BREATHING' },
  { value: 156, name: 'SPELL_AURA_MOD_REPUTATION_GAIN' },
  { value: 157, name: 'SPELL_AURA_PET_DAMAGE_MULTI' },
  { value: 158, name: 'SPELL_AURA_MOD_SHIELD_BLOCKVALUE' },
  { value: 159, name: 'SPELL_AURA_NO_PVP_CREDIT' },
  { value: 160, name: 'SPELL_AURA_MOD_AOE_AVOIDANCE' },
  { value: 161, name: 'SPELL_AURA_MOD_HEALTH_REGEN_IN_COMBAT' },
  { value: 162, name: 'SPELL_AURA_POWER_BURN' },
  { value: 163, name: 'SPELL_AURA_MOD_CRIT_DAMAGE_BONUS' },
  { value: 164, name: 'SPELL_AURA_164' },
  { value: 165, name: 'SPELL_AURA_MELEE_ATTACK_POWER_ATTACKER_BONUS' },
  { value: 166, name: 'SPELL_AURA_MOD_ATTACK_POWER_PCT' },
  { value: 167, name: 'SPELL_AURA_MOD_RANGED_ATTACK_POWER_PCT' },
  { value: 168, name: 'SPELL_AURA_MOD_DAMAGE_DONE_VERSUS' },
  { value: 169, name: 'SPELL_AURA_MOD_CRIT_PERCENT_VERSUS' },
  { value: 170, name: 'SPELL_AURA_DETECT_AMORE' },
  { value: 171, name: 'SPELL_AURA_MOD_SPEED_NOT_STACK' },
  { value: 172, name: 'SPELL_AURA_MOD_MOUNTED_SPEED_NOT_STACK' },
  { value: 173, name: 'SPELL_AURA_173' },
  { value: 174, name: 'SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT' },
  { value: 175, name: 'SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT' },
  { value: 176, name: 'SPELL_AURA_SPIRIT_OF_REDEMPTION' },
  { value: 177, name: 'SPELL_AURA_AOE_CHARM' },
  { value: 178, name: 'SPELL_AURA_MOD_DEBUFF_RESISTANCE' },
  { value: 179, name: 'SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE' },
  { value: 180, name: 'SPELL_AURA_MOD_FLAT_SPELL_DAMAGE_VERSUS' },
  { value: 181, name: 'SPELL_AURA_181' },
  { value: 182, name: 'SPELL_AURA_MOD_RESISTANCE_OF_STAT_PERCENT' },
  { value: 183, name: 'SPELL_AURA_MOD_CRITICAL_THREAT' },
  { value: 184, name: 'SPELL_AURA_MOD_ATTACKER_MELEE_HIT_CHANCE' },
  { value: 185, name: 'SPELL_AURA_MOD_ATTACKER_RANGED_HIT_CHANCE' },
  { value: 186, name: 'SPELL_AURA_MOD_ATTACKER_SPELL_HIT_CHANCE' },
  { value: 187, name: 'SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_CHANCE' },
  { value: 188, name: 'SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_CHANCE' },
  { value: 189, name: 'SPELL_AURA_MOD_RATING' },
  { value: 190, name: 'SPELL_AURA_MOD_FACTION_REPUTATION_GAIN' },
  { value: 191, name: 'SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED' },
  { value: 192, name: 'SPELL_AURA_MOD_MELEE_RANGED_HASTE' },
  { value: 193, name: 'SPELL_AURA_MELEE_SLOW' },
  { value: 194, name: 'SPELL_AURA_MOD_TARGET_ABSORB_SCHOOL' },
  { value: 195, name: 'SPELL_AURA_MOD_TARGET_ABILITY_ABSORB_SCHOOL' },
  { value: 196, name: 'SPELL_AURA_MOD_COOLDOWN' },
  { value: 197, name: 'SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE' },
  { value: 198, name: 'SPELL_AURA_198' },
  { value: 199, name: 'SPELL_AURA_MOD_INCREASES_SPELL_PCT_TO_HIT' },
  { value: 200, name: 'SPELL_AURA_MOD_XP_PCT' },
  { value: 201, name: 'SPELL_AURA_FLY' },
  { value: 202, name: 'SPELL_AURA_IGNORE_COMBAT_RESULT' },
  { value: 203, name: 'SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_DAMAGE' },
  { value: 204, name: 'SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_DAMAGE' },
  { value: 205, name: 'SPELL_AURA_MOD_SCHOOL_CRIT_DMG_TAKEN' },
  { value: 206, name: 'SPELL_AURA_MOD_INCREASE_VEHICLE_FLIGHT_SPEED' },
  { value: 207, name: 'SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED' },
  { value: 208, name: 'SPELL_AURA_MOD_INCREASE_FLIGHT_SPEED' },
  { value: 209, name: 'SPELL_AURA_MOD_MOUNTED_FLIGHT_SPEED_ALWAYS' },
  { value: 210, name: 'SPELL_AURA_MOD_VEHICLE_SPEED_ALWAYS' },
  { value: 211, name: 'SPELL_AURA_MOD_FLIGHT_SPEED_NOT_STACK' },
  { value: 212, name: 'SPELL_AURA_MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT' },
  { value: 213, name: 'SPELL_AURA_MOD_RAGE_FROM_DAMAGE_DEALT' },
  { value: 214, name: 'SPELL_AURA_214' },
  { value: 215, name: 'SPELL_AURA_ARENA_PREPARATION' },
  { value: 216, name: 'SPELL_AURA_HASTE_SPELLS' },
  { value: 217, name: 'SPELL_AURA_MOD_MELEE_HASTE_2' },
  { value: 218, name: 'SPELL_AURA_HASTE_RANGED' },
  { value: 219, name: 'SPELL_AURA_MOD_MANA_REGEN_FROM_STAT' },
  { value: 220, name: 'SPELL_AURA_MOD_RATING_FROM_STAT' },
  { value: 221, name: 'SPELL_AURA_MOD_DETAUNT' },
  { value: 222, name: 'SPELL_AURA_222' },
  { value: 223, name: 'SPELL_AURA_RAID_PROC_FROM_CHARGE' },
  { value: 224, name: 'SPELL_AURA_224' },
  { value: 225, name: 'SPELL_AURA_RAID_PROC_FROM_CHARGE_WITH_VALUE' },
  { value: 226, name: 'SPELL_AURA_PERIODIC_DUMMY' },
  { value: 227, name: 'SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE' },
  { value: 228, name: 'SPELL_AURA_DETECT_STEALTH' },
  { value: 229, name: 'SPELL_AURA_MOD_AOE_DAMAGE_AVOIDANCE' },
  { value: 230, name: 'SPELL_AURA_230' },
  { value: 231, name: 'SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE' },
  { value: 232, name: 'SPELL_AURA_MECHANIC_DURATION_MOD' },
  { value: 233, name: 'SPELL_AURA_CHANGE_MODEL_FOR_ALL_HUMANOIDS' },
  { value: 234, name: 'SPELL_AURA_MECHANIC_DURATION_MOD_NOT_STACK' },
  { value: 235, name: 'SPELL_AURA_MOD_DISPEL_RESIST' },
  { value: 236, name: 'SPELL_AURA_CONTROL_VEHICLE' },
  { value: 237, name: 'SPELL_AURA_MOD_SPELL_DAMAGE_OF_ATTACK_POWER' },
  { value: 238, name: 'SPELL_AURA_MOD_SPELL_HEALING_OF_ATTACK_POWER' },
  { value: 239, name: 'SPELL_AURA_MOD_SCALE_2' },
  { value: 240, name: 'SPELL_AURA_MOD_EXPERTISE' },
  { value: 241, name: 'SPELL_AURA_FORCE_MOVE_FORWARD' },
  { value: 242, name: 'SPELL_AURA_MOD_SPELL_DAMAGE_FROM_HEALING' },
  { value: 243, name: 'SPELL_AURA_MOD_FACTION' },
  { value: 244, name: 'SPELL_AURA_COMPREHEND_LANGUAGE' },
  { value: 245, name: 'SPELL_AURA_MOD_AURA_DURATION_BY_DISPEL' },
  { value: 246, name: 'SPELL_AURA_MOD_AURA_DURATION_BY_DISPEL_NOT_STACK' },
  { value: 247, name: 'SPELL_AURA_CLONE_CASTER' },
  { value: 248, name: 'SPELL_AURA_MOD_COMBAT_RESULT_CHANCE' },
  { value: 249, name: 'SPELL_AURA_CONVERT_RUNE' },
  { value: 250, name: 'SPELL_AURA_MOD_INCREASE_HEALTH_2' },
  { value: 251, name: 'SPELL_AURA_MOD_ENEMY_DODGE' },
  { value: 252, name: 'SPELL_AURA_MOD_SPEED_SLOW_ALL' },
  { value: 253, name: 'SPELL_AURA_MOD_BLOCK_CRIT_CHANCE' },
  { value: 254, name: 'SPELL_AURA_MOD_DISARM_OFFHAND' },
  { value: 255, name: 'SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT' },
  { value: 256, name: 'SPELL_AURA_NO_REAGENT_USE' },
  { value: 257, name: 'SPELL_AURA_MOD_TARGET_RESIST_BY_SPELL_CLASS' },
  { value: 258, name: 'SPELL_AURA_258' },
  { value: 259, name: 'SPELL_AURA_MOD_HOT_PCT' },
  { value: 260, name: 'SPELL_AURA_SCREEN_EFFECT' },
  { value: 261, name: 'SPELL_AURA_PHASE' },
  { value: 262, name: 'SPELL_AURA_ABILITY_IGNORE_AURASTATE' },
  { value: 263, name: 'SPELL_AURA_ALLOW_ONLY_ABILITY' },
  { value: 264, name: 'SPELL_AURA_264' },
  { value: 265, name: 'SPELL_AURA_265' },
  { value: 266, name: 'SPELL_AURA_266' },
  { value: 267, name: 'SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL' },
  { value: 268, name: 'SPELL_AURA_MOD_ATTACK_POWER_OF_STAT_PERCENT' },
  { value: 269, name: 'SPELL_AURA_MOD_IGNORE_TARGET_RESIST' },
  { value: 270, name: 'SPELL_AURA_MOD_ABILITY_IGNORE_TARGET_RESIST' },
  { value: 271, name: 'SPELL_AURA_MOD_DAMAGE_FROM_CASTER' },
  { value: 272, name: 'SPELL_AURA_IGNORE_MELEE_RESET' },
  { value: 273, name: 'SPELL_AURA_X_RAY' },
  { value: 274, name: 'SPELL_AURA_ABILITY_CONSUME_NO_AMMO' },
  { value: 275, name: 'SPELL_AURA_MOD_IGNORE_SHAPESHIFT' },
  { value: 276, name: 'SPELL_AURA_MOD_DAMAGE_DONE_FOR_MECHANIC' },
  { value: 277, name: 'SPELL_AURA_MOD_MAX_AFFECTED_TARGETS' },
  { value: 278, name: 'SPELL_AURA_MOD_DISARM_RANGED' },
  { value: 279, name: 'SPELL_AURA_INITIALIZE_IMAGES' },
  { value: 280, name: 'SPELL_AURA_MOD_ARMOR_PENETRATION_PCT' },
  { value: 281, name: 'SPELL_AURA_MOD_HONOR_GAIN_PCT' },
  { value: 282, name: 'SPELL_AURA_MOD_BASE_HEALTH_PCT' },
  { value: 283, name: 'SPELL_AURA_MOD_HEALING_RECEIVED' },
  { value: 284, name: 'SPELL_AURA_LINKED' },
  { value: 285, name: 'SPELL_AURA_MOD_ATTACK_POWER_OF_ARMOR' },
  { value: 286, name: 'SPELL_AURA_ABILITY_PERIODIC_CRIT' },
  { value: 287, name: 'SPELL_AURA_DEFLECT_SPELLS' },
  { value: 288, name: 'SPELL_AURA_IGNORE_HIT_DIRECTION' },
  { value: 289, name: 'SPELL_AURA_289' },
  { value: 290, name: 'SPELL_AURA_MOD_CRIT_PCT' },
  { value: 291, name: 'SPELL_AURA_MOD_XP_QUEST_PCT' },
  { value: 292, name: 'SPELL_AURA_OPEN_STABLE' },
  { value: 293, name: 'SPELL_AURA_OVERRIDE_SPELLS' },
  { value: 294, name: 'SPELL_AURA_PREVENT_REGENERATE_POWER' },
  { value: 295, name: 'SPELL_AURA_295' },
  { value: 296, name: 'SPELL_AURA_SET_VEHICLE_ID' },
  { value: 297, name: 'SPELL_AURA_BLOCK_SPELL_FAMILY' },
  { value: 298, name: 'SPELL_AURA_STRANGULATE' },
  { value: 299, name: 'SPELL_AURA_299' },
  { value: 300, name: 'SPELL_AURA_SHARE_DAMAGE_PCT' },
  { value: 301, name: 'SPELL_AURA_SCHOOL_HEAL_ABSORB' },
  { value: 302, name: 'SPELL_AURA_302' },
  { value: 303, name: 'SPELL_AURA_MOD_DAMAGE_DONE_VERSUS_AURASTATE' },
  { value: 304, name: 'SPELL_AURA_MOD_FAKE_INEBRIATE' },
  { value: 305, name: 'SPELL_AURA_MOD_MINIMUM_SPEED' },
  { value: 306, name: 'SPELL_AURA_306' },
  { value: 307, name: 'SPELL_AURA_HEAL_ABSORB_TEST' },
  { value: 308, name: 'SPELL_AURA_MOD_CRIT_CHANCE_FOR_CASTER' },
  { value: 309, name: 'SPELL_AURA_309' },
  { value: 310, name: 'SPELL_AURA_MOD_CREATURE_AOE_DAMAGE_AVOIDANCE' },
  { value: 311, name: 'SPELL_AURA_311' },
  { value: 312, name: 'SPELL_AURA_312' },
  { value: 313, name: 'SPELL_AURA_313' },
  { value: 314, name: 'SPELL_AURA_PREVENT_RESURRECTION' },
  { value: 315, name: 'SPELL_AURA_UNDERWATER_WALKING' },
  { value: 316, name: 'SPELL_AURA_PERIODIC_HASTE' },
];
