import { Option } from '../../types/general';

export const TOTEM_CATEGORY: Option[] = [
  { value: 1, name: 'Skinning Knife (OLD)' },
  { value: 2, name: 'Earth Totem' },
  { value: 3, name: 'Air Totem' },
  { value: 4, name: 'Fire Totem' },
  { value: 5, name: 'Water Totem' },
  { value: 6, name: 'Runed Copper Rod' },
  { value: 7, name: 'Runed Silver Rod' },
  { value: 8, name: 'Runed Golden Rod' },
  { value: 9, name: 'Runed Truesilver Rod' },
  { value: 10, name: 'Runed Arcanite Rod' },
  { value: 11, name: 'Mining Pick (OLD)' },
  { value: 12, name: "Philosopher's Stone" },
  { value: 13, name: 'Blacksmith Hammer (OLD)' },
  { value: 14, name: 'Arclight Spanner' },
  { value: 15, name: 'Gyromatic Micro-Adjustor' },
  { value: 21, name: 'Master Totem' },
  { value: 41, name: 'Runed Fel Iron Rod' },
  { value: 62, name: 'Runed Adamantite Rod' },
  { value: 63, name: 'Runed Eternium Rod' },
  { value: 81, name: 'Hollow Quill' },
  { value: 101, name: 'Runed Azurite Rod' },
  { value: 121, name: 'Virtuoso Inking Set' },
  { value: 141, name: 'Drums' },
  { value: 161, name: 'Gnomish Army Knife' },
  { value: 162, name: 'Blacksmith Hammer' },
  { value: 165, name: 'Mining Pick' },
  { value: 166, name: 'Skinning Knife' },
  { value: 167, name: 'Hammer Pick' },
  { value: 168, name: 'Bladed Pickaxe' },
  { value: 169, name: 'Flint and Tinder' },
  { value: 189, name: 'Runed Cobalt Rod' },
  { value: 190, name: 'Runed Titanium Rod' },
];
