import { Option } from '@keira/shared/constants';

export const CREATURE_FAMILY: Option[] = [
  { value: 0, name: 'None' },
  { value: 1, name: 'Wolf' },
  { value: 2, name: 'Cat' },
  { value: 3, name: 'Spider' },
  { value: 4, name: 'Bear' },
  { value: 5, name: 'Boar' },
  { value: 6, name: 'Crocolisk' },
  { value: 7, name: 'Carrion Bird' },
  { value: 8, name: 'Crab' },
  { value: 9, name: 'Gorilla' },
  { value: 11, name: 'Raptor' },
  { value: 12, name: 'Tallstrider' },
  { value: 15, name: 'Felhunter' },
  { value: 16, name: 'Voidwalker' },
  { value: 17, name: 'Succubus' },
  { value: 19, name: 'Doomguard' },
  { value: 20, name: 'Scorpid' },
  { value: 21, name: 'Turtle' },
  { value: 23, name: 'Imp' },
  { value: 24, name: 'Bat' },
  { value: 25, name: 'Hyena' },
  { value: 26, name: 'Bird of Prey' },
  { value: 27, name: 'Wind Serpent' },
  { value: 28, name: 'Remote Control' },
  { value: 29, name: 'Felguard' },
  { value: 30, name: 'Dragonhawk' },
  { value: 31, name: 'Ravager' },
  { value: 32, name: 'Warp Stalker' },
  { value: 33, name: 'Sporebat' },
  { value: 34, name: 'Nether Ray' },
  { value: 35, name: 'Serpent' },
  { value: 37, name: 'Moth' },
  { value: 38, name: 'Chimaera' },
  { value: 39, name: 'Devilsaur' },
  { value: 40, name: 'Ghoul' },
  { value: 41, name: 'Silithid' },
  { value: 42, name: 'Worm' },
  { value: 43, name: 'Rhino' },
  { value: 44, name: 'Wasp' },
  { value: 45, name: 'Core Hound' },
  { value: 46, name: 'Spirit Beast' },
];
