import { TableRow } from './general';

export const SPELL_DBC_TABLE = 'spell_dbc';
export const SPELL_DBC_CUSTOM_STARTING_ID = 200000;
export const SPELL_DBC_ID = 'ID';
export const SPELL_DBC_NAME = 'Name_Lang_enUS';
export const SPELL_DBC_SEARCH_FIELDS = [
  SPELL_DBC_ID,
  SPELL_DBC_NAME,
];

export class SpellDbc extends TableRow {
  ID: number = 0;
  Category: number = 0;
  DispelType: number = 0;
  Mechanic: number = 0;
  Attributes: number = 0; // TODO
  AttributesEx: number = 0; // TODO
  AttributesExB: number = 0; // TODO
  AttributesExC: number = 0; // TODO
  AttributesExD: number = 0; // TODO
  AttributesExE: number = 0; // TODO
  AttributesExF: number = 0; // TODO
  AttributesExG: number = 0; // TODO
  ShapeshiftMask: number = 0; // TODO
  unk_320_2: number = 0; // TODO
  ShapeshiftExclude: number = 0; // TODO
  unk_320_3: number = 0; // TODO
  Targets: number = 0;
  TargetCreatureType: number = 0; // TODO
  RequiresSpellFocus: number = 0; // TODO
  FacingCasterFlags: number = 0; // TODO
  CasterAuraState: number = 0; // TODO
  TargetAuraState: number = 0; // TODO
  ExcludeCasterAuraState: number = 0; // TODO
  ExcludeTargetAuraState: number = 0; // TODO
  CasterAuraSpell: number = 0; // TODO
  TargetAuraSpell: number = 0; // TODO
  ExcludeCasterAuraSpell: number = 0; // TODO
  ExcludeTargetAuraSpell: number = 0; // TODO
  CastingTimeIndex: number = 0; // TODO
  RecoveryTime: number = 0; // TODO
  CategoryRecoveryTime: number = 0; // TODO
  InterruptFlags: number = 0; // TODO
  AuraInterruptFlags: number = 0; // TODO
  ChannelInterruptFlags: number = 0; // TODO
  ProcTypeMask: number = 0;
  ProcChance: number = 0;
  ProcCharges: number = 0;
  MaxLevel: number = 0; // TODO
  BaseLevel: number = 0; // TODO
  SpellLevel: number = 0; // TODO
  DurationIndex: number = 0; // TODO
  PowerType: number = 0; // TODO
  ManaCost: number = 0; // TODO
  ManaCostPerLevel: number = 0; // TODO
  ManaPerSecond: number = 0; // TODO
  ManaPerSecondPerLevel: number = 0; // TODO
  RangeIndex: number = 0; // TODO
  Speed: number = 0; // TODO
  ModalNextSpell: number = 0; // TODO
  CumulativeAura: number = 0; // TODO
  Totem_1: number = 0; // TODO
  Totem_2: number = 0; // TODO
  Reagent_1: number = 0; // TODO
  Reagent_2: number = 0; // TODO
  Reagent_3: number = 0; // TODO
  Reagent_4: number = 0; // TODO
  Reagent_5: number = 0; // TODO
  Reagent_6: number = 0; // TODO
  Reagent_7: number = 0; // TODO
  Reagent_8: number = 0; // TODO
  ReagentCount_1: number = 0; // TODO
  ReagentCount_2: number = 0; // TODO
  ReagentCount_3: number = 0; // TODO
  ReagentCount_4: number = 0; // TODO
  ReagentCount_5: number = 0; // TODO
  ReagentCount_6: number = 0; // TODO
  ReagentCount_7: number = 0; // TODO
  ReagentCount_8: number = 0; // TODO
  EquippedItemClass: number = 0; // TODO
  EquippedItemSubclass: number = 0; // TODO
  EquippedItemInvTypes: number = 0; // TODO
  Effect_1: number = 0; // TODO
  Effect_2: number = 0; // TODO
  Effect_3: number = 0; // TODO
  EffectDieSides_1: number = 0; // TODO
  EffectDieSides_2: number = 0; // TODO
  EffectDieSides_3: number = 0; // TODO
  EffectRealPointsPerLevel_1: number = 0; // TODO
  EffectRealPointsPerLevel_2: number = 0; // TODO
  EffectRealPointsPerLevel_3: number = 0; // TODO
  EffectBasePoints_1: number = 0; // TODO
  EffectBasePoints_2: number = 0; // TODO
  EffectBasePoints_3: number = 0; // TODO
  EffectMechanic_1: number = 0; // TODO
  EffectMechanic_2: number = 0; // TODO
  EffectMechanic_3: number = 0; // TODO
  ImplicitTargetA_1: number = 0; // TODO
  ImplicitTargetA_2: number = 0; // TODO
  ImplicitTargetA_3: number = 0; // TODO
  ImplicitTargetB_1: number = 0; // TODO
  ImplicitTargetB_2: number = 0; // TODO
  ImplicitTargetB_3: number = 0; // TODO
  EffectRadiusIndex_1: number = 0; // TODO
  EffectRadiusIndex_2: number = 0; // TODO
  EffectRadiusIndex_3: number = 0; // TODO
  EffectAura_1: number = 0; // TODO
  EffectAura_2: number = 0; // TODO
  EffectAura_3: number = 0; // TODO
  EffectAuraPeriod_1: number = 0; // TODO
  EffectAuraPeriod_2: number = 0; // TODO
  EffectAuraPeriod_3: number = 0; // TODO
  EffectMultipleValue_1: number = 0; // TODO
  EffectMultipleValue_2: number = 0; // TODO
  EffectMultipleValue_3: number = 0; // TODO
  EffectChainTargets_1: number = 0; // TODO
  EffectChainTargets_2: number = 0; // TODO
  EffectChainTargets_3: number = 0; // TODO
  EffectItemType_1: number = 0; // TODO
  EffectItemType_2: number = 0; // TODO
  EffectItemType_3: number = 0; // TODO
  EffectMiscValue_1: number = 0; // TODO
  EffectMiscValue_2: number = 0; // TODO
  EffectMiscValue_3: number = 0; // TODO
  EffectMiscValueB_1: number = 0; // TODO
  EffectMiscValueB_2: number = 0; // TODO
  EffectMiscValueB_3: number = 0; // TODO
  EffectTriggerSpell_1: number = 0; // TODO
  EffectTriggerSpell_2: number = 0; // TODO
  EffectTriggerSpell_3: number = 0; // TODO
  EffectPointsPerCombo_1: number = 0; // TODO
  EffectPointsPerCombo_2: number = 0; // TODO
  EffectPointsPerCombo_3: number = 0; // TODO
  EffectSpellClassMaskA_1: number = 0; // TODO
  EffectSpellClassMaskA_2: number = 0; // TODO
  EffectSpellClassMaskA_3: number = 0; // TODO
  EffectSpellClassMaskB_1: number = 0; // TODO
  EffectSpellClassMaskB_2: number = 0; // TODO
  EffectSpellClassMaskB_3: number = 0; // TODO
  EffectSpellClassMaskC_1: number = 0; // TODO
  EffectSpellClassMaskC_2: number = 0; // TODO
  EffectSpellClassMaskC_3: number = 0; // TODO
  SpellVisualID_1: number = 0; // TODO
  SpellVisualID_2: number = 0; // TODO
  SpellIconID: number = 0; // TODO
  ActiveIconID: number = 0; // TODO
  SpellPriority: number = 0; // TODO
  Name_Lang_enUS: string = '';
  Name_Lang_enGB: string = '';
  Name_Lang_koKR: string = '';
  Name_Lang_frFR: string = '';
  Name_Lang_deDE: string = '';
  Name_Lang_enCN: string = '';
  Name_Lang_zhCN: string = '';
  Name_Lang_enTW: string = '';
  Name_Lang_zhTW: string = '';
  Name_Lang_esES: string = '';
  Name_Lang_esMX: string = '';
  Name_Lang_ruRU: string = '';
  Name_Lang_ptPT: string = '';
  Name_Lang_ptBR: string = '';
  Name_Lang_itIT: string = '';
  Name_Lang_Unk: string = '';
  Name_Lang_Mask: number = 0; // TODO
  NameSubtext_Lang_enUS: string = '';
  NameSubtext_Lang_enGB: string = '';
  NameSubtext_Lang_koKR: string = '';
  NameSubtext_Lang_frFR: string = '';
  NameSubtext_Lang_deDE: string = '';
  NameSubtext_Lang_enCN: string = '';
  NameSubtext_Lang_zhCN: string = '';
  NameSubtext_Lang_enTW: string = '';
  NameSubtext_Lang_zhTW: string = '';
  NameSubtext_Lang_esES: string = '';
  NameSubtext_Lang_esMX: string = '';
  NameSubtext_Lang_ruRU: string = '';
  NameSubtext_Lang_ptPT: string = '';
  NameSubtext_Lang_ptBR: string = '';
  NameSubtext_Lang_itIT: string = '';
  NameSubtext_Lang_Unk: string = '';
  NameSubtext_Lang_Mask: number = 0; // TODO
  Description_Lang_enUS: string = '';
  Description_Lang_enGB: string = '';
  Description_Lang_koKR: string = '';
  Description_Lang_frFR: string = '';
  Description_Lang_deDE: string = '';
  Description_Lang_enCN: string = '';
  Description_Lang_zhCN: string = '';
  Description_Lang_enTW: string = '';
  Description_Lang_zhTW: string = '';
  Description_Lang_esES: string = '';
  Description_Lang_esMX: string = '';
  Description_Lang_ruRU: string = '';
  Description_Lang_ptPT: string = '';
  Description_Lang_ptBR: string = '';
  Description_Lang_itIT: string = '';
  Description_Lang_Unk: string = '';
  Description_Lang_Mask: number = 0; // TODO
  AuraDescription_Lang_enUS: string = '';
  AuraDescription_Lang_enGB: string = '';
  AuraDescription_Lang_koKR: string = '';
  AuraDescription_Lang_frFR: string = '';
  AuraDescription_Lang_deDE: string = '';
  AuraDescription_Lang_enCN: string = '';
  AuraDescription_Lang_zhCN: string = '';
  AuraDescription_Lang_enTW: string = '';
  AuraDescription_Lang_zhTW: string = '';
  AuraDescription_Lang_esES: string = '';
  AuraDescription_Lang_esMX: string = '';
  AuraDescription_Lang_ruRU: string = '';
  AuraDescription_Lang_ptPT: string = '';
  AuraDescription_Lang_ptBR: string = '';
  AuraDescription_Lang_itIT: string = '';
  AuraDescription_Lang_Unk: string = '';
  AuraDescription_Lang_Mask: number = 0; // TODO
  ManaCostPct: number = 0; // TODO
  StartRecoveryCategory: number = 0; // TODO
  StartRecoveryTime: number = 0; // TODO
  MaxTargetLevel: number = 0; // TODO
  SpellClassSet: number = 0; // TODO
  SpellClassMask_1: number = 0; // TODO
  SpellClassMask_2: number = 0; // TODO
  SpellClassMask_3: number = 0; // TODO
  MaxTargets: number = 0; // TODO
  DefenseType: number = 0; // TODO
  PreventionType: number = 0; // TODO
  StanceBarOrder: number = 0; // TODO
  EffectChainAmplitude_1: number = 0; // TODO
  EffectChainAmplitude_2: number = 0; // TODO
  EffectChainAmplitude_3: number = 0; // TODO
  MinFactionID: number = 0; // TODO
  MinReputation: number = 0; // TODO
  RequiredAuraVision: number = 0; // TODO
  RequiredTotemCategoryID_1: number = 0; // TODO
  RequiredTotemCategoryID_2: number = 0; // TODO
  RequiredAreasID: number = 0; // TODO
  SchoolMask: number = 0; // TODO
  RuneCostID: number = 0; // TODO
  SpellMissileID: number = 0; // TODO
  PowerDisplayID: number = 0; // TODO
  Field227: number = 0; // TODO
  Field228: number = 0; // TODO
  Field229: number = 0; // TODO
  SpellDescriptionVariableID: number = 0; // TODO
  SpellDifficultyID: number = 0; // TODO
}
